# Open source model and data reviews, for variants / AEs

- Beginning with protein structure NER model, sourced from https://huggingface.co/PDBEurope/BiomedNLP-PubMedBERT-ProteinStructure-NER-v3.1

Entities covered by Melanie's model: Bond Interaction, Chemical, Complex Assembly, Evidence, Experimental Method, Gene, Mutant, Oligomeric State, Protein, Protein State, Protein Type, PTM, Residue Name, Residue Name Number, Residue Number, Residue Range, Site, Species, Structure Element, Taxonomy Domain.

In [2]:
from var_utils import *

In [3]:
## Papers sourced via Claude search in ePMC, selected for having a variety of styles of genetic variant mentions
papers = ["PMC7334197", "PMC12713268", "PMC12465344", "PMC12859152", "PMC12874668"]
papers

['PMC7334197', 'PMC12713268', 'PMC12465344', 'PMC12859152', 'PMC12874668']

In [9]:
import sys, os
HERE = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else os.getcwd()
sys.path.insert(0, os.path.normpath(os.path.join(HERE, '../../../epmc-tools/europmc_dev_tool')))
from spacy_patterns import patterns

In [116]:
# Map look-alike characters -> ASCII equivalents
HOMOGLYPH_MAP = str.maketrans({
    0x0441: 'c',   # Cyrillic с → c
    0x0440: 'p',   # Cyrillic р → p
    0x0435: 'e',   # Cyrillic е → e
    0x0430: 'a',   # Cyrillic а → a
    0x2013: '-',   # en-dash → hyphen
    0x2212: '-',   # minus sign → hyphen
    0x2014: '-',   # em-dash → hyphen
})

def map_to_ascii(text: str) -> str:
    """ 
    Replace homoglyph characters with ASCII equivalents.
    Catches chars which may block terms from being caught by regex.
    E.g. 'с.181T >G', wherein 'с' is a Cyrillic character U+0441.
    This can be confused for ASCII 'c', character U+0063
    """
    return text.translate(HOMOGLYPH_MAP)

In [120]:
import json
import re
import uuid

"""
ePMC patterns file defines database cross-references based on regex patterns
Those useful for variant capture include:
- refsnp (dbSNP)
- gca (INSDC genome assembly accessions)
"""
## Compilation of patterns for HGVS statements
# ── Amino acid codes ────────────────────────────────────────────────────────
_AA3 = r'(?:Ala|Arg|Asn|Asp|Cys|Gln|Glu|Gly|His|Ile|Leu|Lys|Met|Phe|Pro|Ser|Thr|Trp|Tyr|Val|Ter|Sec)'
_AA1 = r'[ACDEFGHIKLMNPQRSTVWY]'

# ── Nucleotide change types (shared by g. c. n. r.) ─────────────────────────
# _NUC_POS   = r'[0-9]+(?:[ \t]*[+\-][ \t]*[0-9]+)?'           # e.g. 76, 1799+2
_NUC_POS = r'(?:\*|-)?[0-9]+(?:[ \t]*[+\-][ \t]*[0-9]+)?'
_NUC_RANGE = r'[0-9]+(?:[ \t]*[+\-][ \t]*[0-9]+)?[ \t]*_[ \t]*[0-9]+(?:[ \t]*[+\-][ \t]*[0-9]+)?' # e.g. 76_78
_NUC_BASE  = r'[ACGTUacgtu]'
_SUBST = rf'{_NUC_POS}\s*{_NUC_BASE}\s*>\s*{_NUC_BASE}' # substitution:  A>T, considerate of () // whitespace

_NUC_CHANGE = (
    r'(?:'
    rf'{_SUBST}'
    rf'|(?:{_NUC_RANGE}|{_NUC_POS})[ \t]*delins[ \t]*{_NUC_BASE}+' # indel:    76_78delinsAT
    rf'|(?:{_NUC_RANGE}|{_NUC_POS})[ \t]*del[ \t]*{_NUC_BASE}*'    # deletion: 76del / 76_78del
    rf'|(?:{_NUC_RANGE}|{_NUC_POS})[ \t]*dup[ \t]*{_NUC_BASE}*'    # duplication
    rf'|{_NUC_RANGE}[ \t]*ins[ \t]*{_NUC_BASE}+'                   # insertion: 76_77insA
    rf'|{_NUC_RANGE}[ \t]*inv'                                     # inversion
    r')'
)

# ── Per-prefix patterns ──────────────────────────────────────────────────────
HGVS_GENOMIC  = rf'g\.{_NUC_CHANGE}'                # g.140453136A>T
HGVS_CODING   = rf'c\.{_NUC_CHANGE}'                # c.1799T>A
HGVS_NCRNA    = rf'n\.{_NUC_CHANGE}'                # n.45G>C
HGVS_RNA      = rf'r\.{_NUC_CHANGE}'                # r.76a>u

HGVS_PROTEIN  = (
    r'\(?p\.\(?(?:'                                  # (p.X) and p.(X) handled
    rf'{_AA3}[0-9]+(?:'
        rf'{_AA3}(?:fs(?:Ter[0-9]+)?)?'              # p.Val600Glu / p.Val600GlufsTer5
        rf'|\*'                                      # p.Arg213*  (stop gained)
        rf'|='                                       # p.Val600=  (synonymous)
        rf'|del'                                     # p.Val600del
        rf'|dup'                                     # p.Val600dup
    r')'
    rf'|{_AA1}[0-9]+[{_AA1[1:-1]}*=]'              # p.V600E / p.R213*  (1-letter)
    r')'
)

# ── Optional accession prefix: NM_004333.6: or ENST00000288135.6: ───────────
_ACCESSION = r'(?:\(?[ \t]*(?:NM|NR|NP|NC|NG|XM|XR|ENST|ENSP)_?[0-9]+(?:\.[0-9]+)?[ \t]*\)?[ \t]*:)?'

# ── Combined pattern ─────────────────────────────────────────────────────────
HGVS = re.compile(
    _ACCESSION +
    rf'(?:{HGVS_GENOMIC}|{HGVS_CODING}|{HGVS_NCRNA}|{HGVS_RNA}|{HGVS_PROTEIN})'
)

# Star allele suffix — what follows the gene name
_STAR_SUFFIX = re.compile(
    r'\s*\*\s*[0-9]+[A-Za-z]?(?::[0-9]+[A-Za-z]?)*'          # *13, *02:01
    r'(?:\s*\+\s*\*\s*[0-9]+[A-Za-z]?(?::[0-9]+[A-Za-z]?)*)*' # optional: + *2
)

def find_star_alleles(text: str, gene_spans: list[tuple]) -> list[tuple]:
    """
    For identified geneprotein spans, check if star allele notation
    immediately follows. Returns (text, start, end, label) tuples.
    gene_spans: list of (word, start, end, label)
    """
    results = []
    for word, g_start, g_end, label in gene_spans:
        m = _STAR_SUFFIX.match(text, g_end)   # anchored at gene end position
        if m:
            full_span = text[g_start:m.end()]
            results.append((full_span, g_start, m.end(), "Variant"))
        else:
            results.append((word, g_start, g_end, label))
    return results

In [94]:
from transformers import AutoTokenizer
# Load the same tokenizer the pipeline uses
_tokenizer = AutoTokenizer.from_pretrained("pruas/BENT-PubMedBERT-NER-Gene")

def run_gene_ner_chunked(text: str, pipe, max_tokens: int = 400) -> list[dict]:
    """
    Chunk text at token boundaries (not char boundaries) to stay safely
    under the 512-token position embedding limit.
    """
    # Tokenize with char offset mapping, no special tokens
    enc = _tokenizer(
        text,
        return_offsets_mapping=True,
        add_special_tokens=False
    )
    token_ids   = enc["input_ids"]
    offset_map  = enc["offset_mapping"]   # (char_start, char_end) per token
    results = []
    for chunk_start in range(0, len(token_ids), max_tokens):
        chunk_offsets = offset_map[chunk_start : chunk_start + max_tokens]
        char_start    = chunk_offsets[0][0]
        char_end      = chunk_offsets[-1][1]
        chunk_text    = text[char_start:char_end]
        for ent in pipe(chunk_text):
            ent = dict(ent)
            ent["start"] += char_start   # remap to original text offsets
            ent["end"]   += char_start
            results.append(ent)
    return results

In [121]:
from transformers import pipeline

all_tasks = [] # All LabelStudio tasks

### ------ TODO - Should replace BERT model with ePMC data ---------
# BENT-PubMedBERT, labels: gene, protein
ner_gene = pipeline(
    "ner",
    model="pruas/BENT-PubMedBERT-NER-Gene",
    aggregation_strategy="simple"   # merges subword tokens into full spans
)

label_list = ["refsnp", "gca"] # Relevant patterns
var_patterns = [x for x in patterns if x['label'] in label_list]

for pmcid in papers:
    xml_out = get_epmc_full_text(pmcid=pmcid)
    if xml_out is None:
        continue
    parsed  = parse_epmc_xml(pmcid=pmcid, xml_text=xml_out)


    for sec in parsed.sections:
        ls_tasks = [] # Tasks for paper 'pmcid'
        epmc_matches = []

        text = '\n'.join(sec['text'].split(sep='. ')) # Prepare so as to not mess span numbers
        text = map_to_ascii(text) # Catch non-ASCII chars

        for p in var_patterns:
            pattern = p['pattern']
            epmc_matches.extend([(m.group(), m.start(), m.end(), "Variant") for m in re.finditer(pattern, text)])
        matches = [(m.group(), m.start(), m.end(), "Variant") for m in HGVS.finditer(text)]
        matches.extend(epmc_matches) # Gathering matches

        # Add geneprotein matches
        bert_results = run_gene_ner_chunked(text, ner_gene)
        bert_results = [(ent['word'], ent['start'], ent['end'], "GeneProtein") for ent in bert_results]

        # Catch star allele descriptions if present as 'Variant', otherwise keep as 'GeneProtein'
        star_checked = find_star_alleles(text, bert_results)
        matches.extend(star_checked)

        # Add to LabelStudio-compliant json
        for m in matches:
            ls_tasks.append({
                "value": {
                    "start": m[1],
                    "end":   m[2],
                    "text":  m[0],
                    "labels": [m[3]]
                },
                "id":        str(uuid.uuid4())[:10],
                "from_name": "label",
                "to_name":   "text",
                "type":      "labels",
                "origin":    "prediction"  # marks as pre-annotation, not human
            })

        all_tasks.append({
            "data": {
                "text":    text,
                "heading": sec["heading"] or "Body",
                "pmcid":   pmcid,
            },
            "annotations": [
                {
                    "result":       ls_tasks,
                    "was_cancelled": False,
                    "ground_truth": False,
                }
            ]
        })


        ## Just in case - note for doc-level annotation spans instead of by section
        # offset = 0
        #     for sec in results:
        #         for m in HGVS.finditer(sec.text):
        #             doc_start = offset + m.start()
        #             doc_end   = offset + m.end()
        #         offset += len(sec.text)
        ## Old - printout text and matches
        # hgvs = HGVS.findall(sec["text"])
        # if matches:
        #     sec_text = '\n'.join(sec['text'].split(sep='. '))
        #     print(f"\n[{pmcid}] {sec['heading'] or 'Body'}")
        #     print(f"------SECTION TEXT-----\n{sec_text}\n-----------")
        #     for match, start, end in matches:
        #         print(f"  [{start}:{end}]  {match!r}")
        #         print("- - -")
        # else:
        #     continue

output_path = f"./output/genevar_outputs/variants_ls.json"
with open(output_path, "w") as f:
    json.dump(all_tasks, f, indent=2)
print(f"Written {len(all_tasks)} tasks to {output_path}")

Device set to use mps:0
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Written 81 tasks to ./output/genevar_outputs/variants_ls.json

In [123]:
# # Note written case like 'BRAF V600E mutation' not covered
# Extra format examples
extras = [
    "g.140453136A>T",
    "n.45G>C",
    "r.76a>u",
    "c.76_78del",
    "c.76_77insACG",
    "p.Arg213*",
    "p.Val600=",
    "p.V600E",
    "ENST00000288135.6:c.1799T>A",
    '( NM_001184.4 ):c.4405 A > G',
    'p.(Thr1469Ala)',
    '( NM_139076.3 ):c.727 C > G',
    'p.(Leu243Val)',
    '( NM_004448.4 ):c.3565G > C',
    'p.(Gly1189Arg)',
    '( NM_023110.3 ):c.386 A > C',
    'p.(Asp129Ala)',
    '( NM_007194.4 ):c.906 A > C',
    'p.(Glu302Asp)',
    'c.3306 C > G',
    '*1/*1  +  c.940   C  >  A '
]
print("\n-------MORE EXAMPLES--------")
for e in extras:
    m = HGVS.search(e)
    print(f"  {'OK' if m else 'X'}  {e!r:40s}  -> {m.group() if m else 'no match'}")

-------MORE EXAMPLES--------
  OK  'g.140453136A>T'                          -> g.140453136A>T
  OK  'n.45G>C'                                 -> n.45G>C
  OK  'r.76a>u'                                 -> r.76a>u
  OK  'c.76_78del'                              -> c.76_78del
  OK  'c.76_77insACG'                           -> c.76_77insACG
  OK  'p.Arg213*'                               -> p.Arg213*
  OK  'p.Val600='                               -> p.Val600=
  OK  'p.V600E'                                 -> p.V600E
  OK  'ENST00000288135.6:c.1799T>A'             -> ENST00000288135.6:c.1799T>A
  OK  '( NM_001184.4 ):c.4405 A > G'            -> ( NM_001184.4 ):c.4405 A > G
  OK  'p.(Thr1469Ala)'                          -> p.(Thr1469Ala
  OK  '( NM_139076.3 ):c.727 C > G'             -> ( NM_139076.3 ):c.727 C > G
  OK  'p.(Leu243Val)'                           -> p.(Leu243Val
  OK  '( NM_004448.4 ):c.3565G > C'             -> ( NM_004448.4 ):c.3565G > C
  OK  'p.(Gly1189Arg)'                          -> p.(Gly1189Arg
  OK  '( NM_023110.3 ):c.386 A > C'             -> ( NM_023110.3 ):c.386 A > C
  OK  'p.(Asp129Ala)'                           -> p.(Asp129Ala
  OK  '( NM_007194.4 ):c.906 A > C'             -> ( NM_007194.4 ):c.906 A > C
  OK  'p.(Glu302Asp)'                           -> p.(Glu302Asp
  OK  'c.3306 C > G'                            -> c.3306 C > G
  OK  '*1/*1 \u2009+\u2009 c.940 \u2009 C \u2009>\u2009 A '  -> c.940   C  >  A

## NER model testing

In [59]:
BENT_variant = "alvaroalon2/biobert_genetic_ner"
tokenizer, model, id2label = load_model(model_name = BENT_variant)

all_results: dict[str, list[SectionResult]] = {}
context_words = 10
lookback = None # De-duplicates sentences

for pmcid in papers:
    xml_out = get_epmc_full_text(pmcid=pmcid)
    if xml_out is None:
        continue
    parsed  = parse_epmc_xml(pmcid=pmcid, xml_text=xml_out)
    results = run_ner_pipeline(parsed, model=model, tokenizer=tokenizer, id2label=id2label)
    all_results[pmcid] = results
    # preview annotations
    for sec in results:
        if sec.entities:
            for ent in sec.entities:
                context = get_context(sec.text, ent, window=context_words)
                if context == lookback:
                    continue
                print(f"\n[{pmcid}] {sec.heading or 'Body'}")
                print(f"  {ent.label:15s}  {context}")
                lookback = context

/Users/withers/GitProjects/OTAR3088/ner-model/lib/python3.10/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

[PMC7334197] Main
  GENETIC          …sequencing projects have revealed a surprisingly high burden of natural ***pLoF*** variation in the human population, including stop-gained, essential splice, and…

[PMC7334197] Main
  GENETIC          …in identifying potential therapeutic targets: confirmed LoF variants in the ***PCSK9 gene*** have been causally linked to low levels of low-density lipoprotein…

[PMC7334197] Main
  GENETIC          …PCSK9 gene have been causally linked to low levels of ***low-density lipoprotein cholesterol 6*** , and have ultimately led to the development of several…

[PMC7334197] Main
  GENETIC          …have ultimately led to the development of several inhibitors of ***PCSK9*** that are now in clinical use for the reduction of…

[PMC7334197] Main
  GENETIC          …the reduction of cardiovascular disease risk. A systematic catalogue of ***pLoF variants*** in humans and the classification of genes along a spectrum…

[PMC7334197] Main
  GENETIC          …rearrangements of DNA) is reported 11 . The value of ***pLoF variants*** for the discovery and validation of therapeutic drug targets is…

[PMC7334197] Main
  GENETIC          …datasets is provided to validate the safety of inhibition of ***LRRK2—a*** candidate therapeutic target for Parkinson’s disease 13 . By combining…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …spectrum of effects in between. Throughout this manuscript, we define ***pLoF variants*** to be those that introduce a premature stop (stop-gained), shift-reported…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …splice variants, that are predicted to escape nonsense-mediated decay) to ***pLoF variants*** annotated by the variant effect predictor (Extended Data Fig. 5a…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …using frequency information, we find that this method disproportionately removes ***pLoF variants*** that are common in the population, which are known to…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …as reported pathogenic variation (Fig. 2a ). LOFTEE distinguishes high-confidence ***pLoF variants*** from annotation artefacts, and identifies a set of putative splice…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …(Fig. 2b ). Applying LOFTEE v1.0, we discover 443,769 high-confidence ***pLoF*** variants, of which 413,097 fall on the canonical transcripts of…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …on the canonical transcripts of 16,694 genes. The number of ***pLoF variants*** per individual is consistent with previous reports 1 , and…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …Table 17 ). Fig. 2 Generating a high-confidence set of ***pLoF variants.*** a , The percentage of variants filtered by LOFTEE grouped…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …on the canonical transcripts of 16,694 genes. The number of ***pLoF*** variants per individual is consistent with previous reports 1 ,…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …, MAPS (see Fig. 1c, d ) is shown by ***LOFTEE*** designation and filter. Variants filtered out by LOFTEE exhibit frequency…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …confidence intervals. c , d , The total number of ***pLoF variants*** ( c ), and proportion of genes with more than…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …the landscape of genic tolerance to homozygous inactivation, identifying 4,332 ***pLoF*** variants that are homozygous in at least one individual. Given…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …the landscape of genic tolerance to homozygous inactivation, identifying 4,332 ***pLoF variants*** that are homozygous in at least one individual. Given the…

[PMC7334197] Identifying loss-of-function variants
  GENETIC          …at least one individual. Given the rarity of true homozygous ***LoF*** variants, we expected substantial enrichment of such variants for sequencing…

[PMC7334197] The LoF intolerance of human genes
  GENETIC          …depletion of pLoF variation by comparing the number of observed ***pLoF*** variants against our expectation in the gnomAD exome data from…

[PMC7334197] The LoF intolerance of human genes
  GENETIC          …For this dataset, we computed a median of 17.9 expected ***pLoF variants*** per gene (Fig. 2c ) and found that 72.1% of…

[PMC7334197] The LoF intolerance of human genes
  GENETIC          …and found that 72.1% of genes have more than 10 ***pLoF variants*** (powered to be classified into the most constrained genes) (…

[PMC7334197] The LoF intolerance of human genes
  GENETIC          …of the observed and expected values for the number of ***pLoF variants*** in each gene into the pLI: this metric estimates the…

[PMC7334197] The LoF intolerance of human genes
  GENETIC          …are relatively tolerant of inactivation, including many that contain homozygous ***pLoF*** variants (Extended Data Fig. 7g ). We note that the…

[PMC7334197] Biological properties of constraint
  GENETIC          …gene is expressed (transcripts per million > 0.3), binned by ***LOEUF*** decile, is shown as a violin plot with the mean…

[PMC7334197] Biological properties of constraint
  GENETIC          …genes are more likely to be expressed in several tissues ***(LOEUF*** linear regression r = −0.31; P < 1 × 10…

[PMC7334197] Biological properties of constraint
  GENETIC          …has only 8,128 individuals, our ability to detect constraint against ***pLoF variants*** for individual genes is limited. However, for well-powered genes (expected…

[PMC7334197] Constraint informs disease aetiologies
  GENETIC          …disability/developmental delay (ID/DD) divided by the rate in 2,179 controls. ***pLoF variants*** in the most constrained decile of the genome are approximately…

[PMC7334197] Constraint informs disease aetiologies
  GENETIC          …genomic annotations. Colours alternate by broad phenotype category. Finally, although ***pLoF variants*** are predominantly rare, other more common variation in constrained genes…

[PMC7334197] Constraint informs disease aetiologies
  GENETIC          …5c ), consistent with previous observations in associations between rare ***pLoF variants*** and these phenotypes 29 – 31 . This enrichment persists…

[PMC7334197] Discussion
  GENETIC          …sample sizes and careful analysis of individuals enriched for homozygous ***pLoFs*** (see below) will be useful for distinguishing these possibilities. Furthermore,…

[PMC7334197] Discussion
  GENETIC          …intolerance to inactivation. Despite these caveats, our results demonstrate that ***pLoF*** constraint divides protein-coding genes in a way that correlates usefully…

[PMC7334197] Discussion
  GENETIC          …studies of both rare and common diseases. Examples such as ***PCSK9*** demonstrate the value of human pLoF variants for identifying and…

[PMC7334197] Discussion
  GENETIC          …common diseases. Examples such as PCSK9 demonstrate the value of ***human pLoF variants*** for identifying and validating targets for therapeutic intervention across a…

[PMC7334197] Discussion
  GENETIC          …be paid to a variety of complicating factors when using ***pLoF*** constraint to assess candidates. More valuable information comes from directly…

[PMC7334197] Discussion
  GENETIC          …a companion manuscript that explores the clinical correlates of heterozygous ***pLoF variants*** in the LRRK2 gene, demonstrating that life-long partial inactivation of…

[PMC7334197] Discussion
  GENETIC          …explores the clinical correlates of heterozygous pLoF variants in the ***LRRK2 gene,*** demonstrating that life-long partial inactivation of this gene is likely…

[PMC7334197] Discussion
  GENETIC          …humans 13 . Such examples, and the sheer scale of ***pLoF*** discovery in this dataset, suggest the near-future feasibility and considerable…

[PMC12713268] Abstract
  GENETIC          …a large metropolitan area in 2018. Testing targeted eight recurrent ***BRCA1/2*** founder pathogenic variants using validated real-time PCR assays. Women with…

[PMC12713268] Abstract
  GENETIC          …of clinical outcomes. The primary outcome was the prevalence of ***BRCA1/2 founder variants;*** secondary outcomes included age and family-history profiles, adherence to surveillance,…

[PMC12713268] Abstract
  GENETIC          …and made a median of two visits. Among 402 identified ***BRCA1/2*** pathogenic variant carriers, 386 women (0.36%) had pathogenic variants in…

[PMC12713268] Abstract
  GENETIC          …variant carriers, 386 women (0.36%) had pathogenic variants in the ***BRCA1 gene*** and 16 women (0.01%) had pathogenic variants in the BRCA2…

[PMC12713268] Abstract
  GENETIC          …gene and 16 women (0.01%) had pathogenic variants in the ***BRCA2 gene.*** The BRCA1 variant c.5266dup accounted for 66.2% of all pathogenic…

[PMC12713268] Abstract
  GENETIC          …women (0.01%) had pathogenic variants in the BRCA2 gene. The ***BRCA1 variant c.5266dup*** accounted for 66.2% of all pathogenic variant detected. BRCA1/2 pathogenic…

[PMC12713268] Abstract
  GENETIC          …variant c.5266dup accounted for 66.2% of all pathogenic variant detected. ***BRCA1/2 pathogenic variants*** were significantly associated with a high incidence of cancer in…

[PMC12713268] Abstract
  GENETIC          …systems can enhance early detection rates of cancers associated with ***BRCA1/2 variants,*** ultimately leading to better patient outcomes and personalized healthcare strategies.…

[PMC12713268] Abstract
  GENETIC          …systems can enhance early detection rates of cancers associated with ***BRCA1/2*** variants, ultimately leading to better patient outcomes and personalized healthcare…

[PMC12713268] Abstract
  GENETIC          …The online version contains supplementary material available at 10.1186/s12905-025-04164-6. Keywords: ***BRCA1*** , BRCA2 , Breast cancer, Screening program…

[PMC12713268] Abstract
  GENETIC          …version contains supplementary material available at 10.1186/s12905-025-04164-6. Keywords: BRCA1 , ***BRCA2*** , Breast cancer, Screening program…

[PMC12713268] Background
  GENETIC          …tumorigenesis arises after additional somatic events [ 1 ]. The ***BRCA1/2 genes*** are the most studied hereditary cancer genes [ 1 ,…

[PMC12713268] Background
  GENETIC          …genes [ 1 , 2 ]. Pathogenic/likely pathogenic variants in ***BRCA1/2*** confer high lifetime risks of breast cancer (≈ 70%) and…

[PMC12713268] Background
  GENETIC          …breast cancer (≈ 70%) and ovarian cancer (≈ 44% for ***BRCA1*** ; ≈17% for BRCA2 ) by age 80 [ 3…

[PMC12713268] Background
  GENETIC          …and ovarian cancer (≈ 44% for BRCA1 ; ≈17% for ***BRCA2*** ) by age 80 [ 3 , 4 ]. Genetic…

[PMC12713268] Background
  GENETIC          …3 , 4 ]. Genetic testing for pathogenic variants in ***BRCA1/2 genes*** holds significant relevance in informing risk-reducing strategies for unaffected individuals…

[PMC12713268] Background
  GENETIC          …decisions for affected patients [ 5 ]. The presence of ***BRCA1/2 variants*** is also associated with an increased risk of developing pancreatic…

[PMC12713268] Background
  GENETIC          …ovarian cancer in Russia is application of founder pathogenic variants ***BRCA1*** (с.5266dup, с.181T >G, с.1961del, с.4035del, с.68_69delAG, с.3756_3759del, с.3700_3704del) and BRCA2…

[PMC12713268] Background
  GENETIC          …BRCA1 (с.5266dup, с.181T >G, с.1961del, с.4035del, с.68_69delAG, с.3756_3759del, с.3700_3704del) and ***BRCA2*** (c.5946del) by PCR-panel. “In our region, a small set of…

[PMC12713268] Background
  GENETIC          …by PCR-panel. “In our region, a small set of recurrent ***BRCA1/2 founder pathogenic*** variants accounts for a substantial fraction of hereditary cases, supporting…

[PMC12713268] Background
  GENETIC          …cases [ 10 – 12 ]. We used a limited ***BRCA1/2*** founder-variant panel as a pragmatic first-line test to maximize diagnostic…

[PMC12713268] Background
  GENETIC          …Thus, our study aimed to estimate the frequency of founder ***BRCA1/2 pathogenic variants*** in a metropolitan population of women and to evaluate the…

[PMC12713268] Background
  GENETIC          …Thus, our study aimed to estimate the frequency of founder ***BRCA1/2*** pathogenic variants in a metropolitan population of women and to…

[PMC12713268] Background
  GENETIC          …the clinical value of preventive examinations for detecting malignancies in ***BRCA1/2 pathogenic variants*** carriers.…

[PMC12713268] Genetic testing
  GENETIC          …for the KingFisher Flex system (Thermo Fisher, USA). Eight recurrent ***BRCA1/2*** founder pathogenic variants (Table 1 ) were assayed using four…

[PMC12713268] Genetic testing
  GENETIC          …3809, 3841), per the manufacturer’s instructions. Collectively, these kits target ***BRCA1*** c.68_69delAG (185delAG), c.181T > G (p.Cys61Gly), c.1961del (2080delA), c.3700_3704del (3819del5),…

[PMC12713268] Genetic testing
  GENETIC          …(2080delA), c.3700_3704del (3819del5), c.3756_3759del (3875del4), c.4035delA (4153delA), c.5266dupC (5382insC), and ***BRCA2*** c.5946delT (6174delT); HGVS/rsIDs are provided in Table 1 .…

[PMC12713268] Results
  GENETIC          …of 107300 women, 386 (0.36%) had pathogenic variants in the ***BRCA1 gene*** and 16 (0.01%) in the BRCA2 gene. The allelic frequency…

[PMC12713268] Results
  GENETIC          …variants in the BRCA1 gene and 16 (0.01%) in the ***BRCA2 gene.*** The allelic frequency of founder BRCA1/2 pathogenic variants was 1.87*10…

[PMC12713268] Results
  GENETIC          …(0.01%) in the BRCA2 gene. The allelic frequency of founder ***BRCA1/2*** pathogenic variants was 1.87*10 − 3 . Upon receiving positive…

[PMC12713268] Results
  GENETIC          …counseling and participation in a follow-up monitoring program. Thus, 329 ***BRCA1/2*** pathogenic variants women (consent rate of 81.8%) continued to participate…

[PMC12713268] Results
  GENETIC          …Based on counseling and clinical examination data from women carrying ***BRCA1/2*** pathogenic variants, we compiled a per-variant summary—including the number of…

[PMC12713268] Results
  GENETIC          …find statistically significant differences in obstetric history between carriers of ***BRCA1*** and BRCA2 pathogenic variants, however, a relatively large percentage of…

[PMC12713268] Results
  GENETIC          …significant differences in obstetric history between carriers of BRCA1 and ***BRCA2*** pathogenic variants, however, a relatively large percentage of women have…

[PMC12713268] Results
  GENETIC          …history, we found statistically significant differences between the groups of ***BRCA1 pathogenic*** variants carriers and BRCA2 pathogenic variant carriers in the number…

[PMC12713268] Results
  GENETIC          …differences between the groups of BRCA1 pathogenic variants carriers and ***BRCA2 pathogenic variant*** carriers in the number of women with fibrocystic breast disease…

[PMC12713268] Results
  GENETIC          …overall effectiveness of preventive strategies. We used the cases of ***BRCA1/2 pathogenic variants*** women with cancer from the follow-up cohort and of BRCA1/2…

[PMC12713268] Results
  GENETIC          …variants women with cancer from the follow-up cohort and of ***BRCA1/2 variant-negative*** women obtained from the random sample from the screening participants’…

[PMC12713268] Results
  GENETIC          …significant increase in risk for all types of cancer among ***BRCA1/2 pathogenic*** variant carriers. The risk of second cancer, bilateral breast cancer,…

[PMC12713268] Discussion
  GENETIC          …focus on cost-effectiveness, we prioritized screening for the most common ***BRCA1/2*** founder pathogenic variants prevalent in the population. This strategic decision…

[PMC12713268] Discussion
  GENETIC          …found 0.37%-unselected probands have a founder pathogenic variant in the ***BRCA1/2 gene.*** According to early data, the BRCA1/2 pathogenic variants frequency in…

[PMC12713268] Discussion
  GENETIC          …variant in the BRCA1/2 gene. According to early data, the ***BRCA1/2*** pathogenic variants frequency in the general population is 1:300–800, among…

[PMC12713268] Discussion
  GENETIC          …with breast cancer the incidence of pathogenic variants in the ***BRCA1/2 genes*** in ranges from 0.1 to 25.6% ( BRCA1–0 .1-25.6%; BRCA2–0…

[PMC12713268] Discussion
  GENETIC          …the BRCA1/2 genes in ranges from 0.1 to 25.6% ( ***BRCA1–0*** .1-25.6%; BRCA2–0 .1-0.5%), in patients with ovarian cancer - from…

[PMC12713268] Discussion
  GENETIC          …genes in ranges from 0.1 to 25.6% ( BRCA1–0 .1-25.6%; ***BRCA2–0*** .1-0.5%), in patients with ovarian cancer - from 0.3 to…

[PMC12713268] Discussion
  GENETIC          …patients with ovarian cancer - from 0.3 to 35% ( ***BRCA1–10*** .29- 27%; BRCA2–0 .3-8%) [ 22 ]. The variant с.5266dup…

[PMC12713268] Discussion
  GENETIC          …cancer - from 0.3 to 35% ( BRCA1–10 .29- 27%; ***BRCA2–0*** .3-8%) [ 22 ]. The variant с.5266dup is predominant and…

[PMC12713268] Discussion
  GENETIC          …(gnomAD) showed that four pathogenic variants were more frequent ( ***BRCA1*** с.5266dup, с.181T >G, с.1961del, с.4035del) and one of the pathogenic…

[PMC12713268] Discussion
  GENETIC          …and one of the pathogenic variants was less frequent ( ***BRCA2 c.5946del)*** than was shown previously for the European (non-Finnish) population. Notably,…

[PMC12713268] Discussion
  GENETIC          …was shown previously for the European (non-Finnish) population. Notably, the ***BRCA2*** c.5946del pathogenic variant identified in our study is exclusively associated…

[PMC12713268] Discussion
  GENETIC          …reported in non-Ashkenazi Jewish populations [ 23 ]. Similarly, the ***BRCA1 c.185delAG*** pathogenic variant we detected has a strong predominance in Jewish…

[PMC12713268] Discussion
  GENETIC          …reported in non-Ashkenazi Jewish populations [ 23 ]. Similarly, the ***BRCA1 c.185delAG pathogenic variant*** we detected has a strong predominance in Jewish populations, particularly…

[PMC12713268] Discussion
  GENETIC          …component in our study population Since the allelic frequency of ***BRCA1 с.3700_3704del*** was not present in the gnomAD, for comparison we used…

[PMC12713268] Discussion
  GENETIC          …in the gnomAD, for comparison we used a study of ***BRCA1 pathogenic variant*** frequency in the Polish population [ 25 ]. In this…

[PMC12713268] Discussion
  GENETIC          …in the Polish population [ 25 ]. In this study, ***BRCA1 c.3700_3704del*** frequency (5.10*10 − 4 ) was 9.12 times higher than…

[PMC12713268] Discussion
  GENETIC          …during pregnancy or within 12 months postpartum—appears relatively rare among ***BRCA1/2*** carriers but more frequent than in the general population. Renata…

[PMC12713268] Discussion
  GENETIC          …et al. reported an overall PABC incidence of 2.05% among ***BRCA1/2*** carriers, higher than in the general population [ 26 ].…

[PMC12713268] Discussion
  GENETIC          …find statistically significant differences in obstetric history between carriers of ***BRCA1*** and BRCA2 pathogenic variants. The relationship between BRCA1/2 mutations and…

[PMC12713268] Discussion
  GENETIC          …significant differences in obstetric history between carriers of BRCA1 and ***BRCA2 pathogenic variants.*** The relationship between BRCA1/2 mutations and miscarriage rates remains a…

[PMC12713268] Discussion
  GENETIC          …carriers of BRCA1 and BRCA2 pathogenic variants. The relationship between ***BRCA1/2*** mutations and miscarriage rates remains a topic of ongoing debate…


### Testing annotation of ~variants with PDBe model

In [3]:
pdbe_model = "PDBEurope/BiomedNLP-PubMedBERT-ProteinStructure-NER-v3.1"
tokenizer, model, id2label = load_model(model_name = pdbe_model)

all_results: dict[str, list[SectionResult]] = {}
context_words = 10
lookback = None # De-duplicates sentences

for pmcid in papers:
    xml_out = get_epmc_full_text(pmcid=pmcid)
    if xml_out is None:
        continue
    parsed  = parse_epmc_xml(pmcid=pmcid, xml_text=xml_out)
    results = run_ner_pipeline(parsed, model=model, tokenizer=tokenizer, id2label=id2label)
    all_results[pmcid] = results
    # preview annotations
    for sec in results:
        if sec.entities:
            for ent in sec.entities:
                if ent.label == 'mutant':
                    context = get_context(sec.text, ent, window=context_words)
                    if context == lookback:
                        continue
                    print(f"\n[{pmcid}] {sec.heading or 'Body'}")
                    print(f"  {ent.label:15s}  {context}")
                    lookback = context

/Users/withers/GitProjects/OTAR3088/ner-model/lib/python3.10/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

[PMC12713268] Abstract
  mutant           …had pathogenic variants in the BRCA2 gene. The BRCA1 variant ***c.5266dup*** accounted for 66.2% of all pathogenic variant detected. BRCA1/2 pathogenic…

[PMC12713268] Genetic testing
  mutant           …Collectively, these kits target BRCA1 c.68_69delAG (185delAG), c.181T > G ***(p.Cys61Gly),*** c.1961del (2080delA), c.3700_3704del (3819del5), c.3756_3759del (3875del4), c.4035delA (4153delA), c.5266dupC (5382insC),…

[PMC12713268] Discussion
  mutant           …BRCA1–10 .29- 27%; BRCA2–0 .3-8%) [ 22 ]. The variant ***с.5266dup*** is predominant and is found in 57–68%, the c.4153del pathogenic…

[PMC12713268] Discussion
  mutant           …variant с.5266dup is predominant and is found in 57–68%, the ***c.4153del*** pathogenic variant ranks second - in 12.5% of all BRCA-associated…

[PMC12713268] Discussion
  mutant           …showed that four pathogenic variants were more frequent ( BRCA1 ***с.5266dup,*** с.181T >G, с.1961del, с.4035del) and one of the pathogenic variants…

[PMC12713268] Discussion
  mutant           …that four pathogenic variants were more frequent ( BRCA1 с.5266dup, ***с.181T >G,*** с.1961del, с.4035del) and one of the pathogenic variants was less…

[PMC12713268] Discussion
  mutant           …pathogenic variants were more frequent ( BRCA1 с.5266dup, с.181T >G, ***с.1961del,*** с.4035del) and one of the pathogenic variants was less frequent…

[PMC12713268] Discussion
  mutant           …variants were more frequent ( BRCA1 с.5266dup, с.181T >G, с.1961del, ***с.4035del)*** and one of the pathogenic variants was less frequent (…

[PMC12713268] Discussion
  mutant           …one of the pathogenic variants was less frequent ( BRCA2 ***c.5946del)*** than was shown previously for the European (non-Finnish) population. Notably,…

[PMC12713268] Discussion
  mutant           …shown previously for the European (non-Finnish) population. Notably, the BRCA2 ***c.5946del*** pathogenic variant identified in our study is exclusively associated with…

[PMC12713268] Discussion
  mutant           …in non-Ashkenazi Jewish populations [ 23 ]. Similarly, the BRCA1 ***c.185delAG*** pathogenic variant we detected has a strong predominance in Jewish…

[PMC12713268] Discussion
  mutant           …in our study population Since the allelic frequency of BRCA1 ***с.3700_3704del*** was not present in the gnomAD, for comparison we used…

[PMC12713268] Discussion
  mutant           …the Polish population [ 25 ]. In this study, BRCA1 ***c.3700_3704del*** frequency (5.10*10 − 4 ) was 9.12 times higher than…

[PMC12465344] Pathogenic and likely pathogenic variants
  mutant           …Colon Cancer MLH1 Missense ( NM_000249.4 ):c.350 C > T ***p.(Thr117Met)*** Pathogenic rs63750781 47.3% No P2 Male/66 Colon Cancer MLH1 Missense…

[PMC12465344] Pathogenic and likely pathogenic variants
  mutant           …Colon Cancer MLH1 Missense ( NM_000249.4 ):c.244 A > G ***p.(Thr82Ala)*** Pathogenic rs587778998 46.1% No P3 Female/48 Right Colon Cancer PMS2…

[PMC12465344] Pathogenic and likely pathogenic variants
  mutant           …46.5% No P9 Male/69 Colon Cancer ATM Splice ( NM_000051.4 ***):c.6808-1G > A*** Pathogenic Novel 43.8% No P10 Female/49 Colon Cancer MUC16 Frameshift…

[PMC12465344] Pathogenic and likely pathogenic variants
  mutant           …43.8% No P10 Female/49 Colon Cancer MUC16 Frameshift ( NM_024690.2 ***):c.37524del*** p.(Thr12509ProfsTer47) Likely Pathogenic Novel 47.9% No dbSNP Single-nucleotide polymorphism database,…

[PMC12465344] Molecular analysis of patients with Lynch syndrome
  mutant           …in MLH1 were identified in Patients P1 and P2 as ***p.(Thr117Met)*** [ 17 ] and p.(Thr82Ala) [ 18 ], respectively. Patient…

[PMC12465344] Molecular analysis of patients with Lynch syndrome
  mutant           …Patients P1 and P2 as p.(Thr117Met) [ 17 ] and ***p.(Thr82Ala)*** [ 18 ], respectively. Patient P3 carried a novel pathogenic…

[PMC12465344] Molecular analysis of patients with Lynch syndrome
  mutant           …], respectively. Patient P3 carried a novel pathogenic nonsense variant, ***p.(Lys433Ter),*** in the PMS2 gene. Similarly, Patient P4 harbored a novel…

[PMC12465344] Molecular analysis of patients with Lynch syndrome
  mutant           …gene. Similarly, Patient P4 harbored a novel pathogenic frameshift variant, ***p.(Phe726SerfsTer10),*** in the MSH6 gene. All patients developed colorectal cancer, with…

[PMC12465344] Molecular analysis of patients with polyposis
  mutant           …of familial adenomatous polyposis. Patient P5 harbored a nonsense variant ***p.(Arg213Ter),*** whereas Patient P6 exhibited p.(Arg232Ter), both of which are well…

[PMC12465344] Molecular analysis of patients with polyposis
  mutant           …P5 harbored a nonsense variant p.(Arg213Ter), whereas Patient P6 exhibited ***p.(Arg232Ter),*** both of which are well documented as pathogenic [ 19…

[PMC12465344] Molecular analysis of patients with polyposis
  mutant           …, 20 ]. Additionally, a single variant of uncertain significance, ***p.(Ile223Val),*** in the MUTYH gene was detected in one patient (P11)…

[PMC12465344] Molecular analysis of patients with an unknown inherited syndrome predisposing to CRC
  mutant           …familial colon and pancreas cancers. A likely pathogenic missense variant ***p.(Leu183Phe),*** in CHEK2 was identified in P8, a patient with familial…

[PMC12465344] Molecular analysis of patients with an unknown inherited syndrome predisposing to CRC
  mutant           …inherited cancer risk. A likely pathogenic novel frameshift germline variant, ***p.(Thr12509ProfsTer47),*** in MUC16 was identified in Patient P10, who presented with…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …Colon Cancer MUTYH Missense ( NM_001128425.2 ):c.667 A > G ***(p.Ile223Val)*** VUS rs200965879 46.1% No Patients with unknown inherited syndromes predisposing…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …big polyp XRCC3 Missense ( NM_001100119.2 ):c.964 C > T ***p.(His322Tyr)*** VUS Novel 47% No P14 Male/68 Stomach and Colon Cancers…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …Sigmoid Colon ATM Missense ( NM_000051.4 ):c.2384 C > T ***p.(Pro795Leu)*** VUS Novel 46.3% No P16 Female/64 Polyps in the colon…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …in the colon SYNE1 Missense ( NM_033071.4 ):c.8102G > A ***p.(Ser2701Asn)*** VUS Novel 44.9% No P17 Female/76 Colon Adeno -carcinoma RAD51D…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …Adeno -carcinoma RAD51D Missense ( NM_002878.4 ):c.412 A > C ***p.(Asn138His)*** VUS rs141690729 46.6% Yes (Maternal) P18 Female/76 Breast and Colon…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …Colon Cancer NF1 Missense ( NM_000267.3 ):c.584 A > G ***p.(Lys195Arg)*** VUS rs587778552 43.5% No P19 Female/63 Colon Cancer ATR Missense…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …Colon Cancer ATR Missense ( NM_001184.4 ):c.4405 A > G ***p.(Thr1469Ala)*** VUS rs78895258 46% No P20 Male/47 Operated Colon Cancer ABRAXAS1…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …Colon Cancer ABRAXAS1 Missense ( NM_139076.3 ):c.727 C > G ***p.(Leu243Val)*** VUS rs755187051 45.5% No P21 Female/39 Colon cancer and Ovarian…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …and Ovarian Metastasis ERBB2 Missense ( NM_004448.4 ):c.3565G > C ***p.(Gly1189Arg)*** VUS Novel 46.7% No P22 Female/66 Rectum and Ovarian Cancers…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …Ovarian Cancers FGFR1 Missense ( NM_023110.3 ):c.386 A > C ***p.(Asp129Ala)*** VUS rs765615419 47% No P23 Female/78 Uterus and Rectum Cancers…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …Rectum Cancers CHEK2 Missense ( NM_007194.4 ):c.906 A > C ***p.(Glu302Asp)*** VUS rs587780190 45.6% No dbSNP Single-nucleotide polymorphism database, HGVS Human…

[PMC12465344] Variants of uncertain significance (VUS)
  mutant           …genes, including PALB2 , in which we found the variant ***c.3306 C > G.*** This variant was found in a patient with breast cancer…

[PMC12465344] Discussion
  mutant           …linked to Li–Fraumeni syndrome [ 31 ]. The specific variants ***1100delC*** and I157T, have been identified as risk variants for colorectal…

[PMC12465344] Discussion
  mutant           …Li–Fraumeni syndrome [ 31 ]. The specific variants 1100delC and ***I157T,*** have been identified as risk variants for colorectal cancer syndromes,…

[PMC12465344] Discussion
  mutant           …VUS were identified in the XRCC3 (c.964 C > T; ***p.(His322Tyr)),*** ATM (c.2384 C > T; p.(Pro795Leu)), and SYNE1 (c.8102G >…

[PMC12465344] Discussion
  mutant           …(c.964 C > T; p.(His322Tyr)), ATM (c.2384 C > T; ***p.(Pro795Leu)),*** and SYNE1 (c.8102G > A; p.(Ser2701Asn)) genes in three families…

[PMC12465344] Discussion
  mutant           …(c.2384 C > T; p.(Pro795Leu)), and SYNE1 (c.8102G > A; ***p.(Ser2701Asn))*** genes in three families with colonic polyps. To our knowledge,…

[PMC12859152] Abstract
  mutant           …confirmation that partial gene and intragenic deletions in CYP2C19 ( ***CYP2C19*37*** and CYP2C19*42 ), enriched in Estonians and Finns, are associated…

[PMC12859152] Abstract
  mutant           …partial gene and intragenic deletions in CYP2C19 ( CYP2C19*37 and ***CYP2C19*42*** ), enriched in Estonians and Finns, are associated with poor…

[PMC12859152] Abstract
  mutant           …offer in vivo evidence of reduced metabolic activity of the ***CYP2D6*124*** allele and a novel missense variant (c.940C>A) in exon 6…

[PMC12859152] Abstract
  mutant           …activity of the CYP2D6*124 allele and a novel missense variant ***(c.940C>A)*** in exon 6 of CYP2D6 . Furthermore, we observed that…

[PMC12859152] Introduction
  mutant           …involving the adjacent CYP2D7 pseudogene in tandem with functional (e.g. ***CYP2D6*13 + *2*** ) or nonfunctional copies of CYP2D6 (e.g. CYP2D6 * 68…

[PMC12859152] Introduction
  mutant           …CYP2D6*13 + *2 ) or nonfunctional copies of CYP2D6 (e.g. ***CYP2D6 * 68 + *4*** ) remains difficult with short-read sequencing 29 . For CYP2C19…

[PMC12859152] Introduction
  mutant           …the Pharmacogene Variation Consortium (PharmVar) 30 catalogues deletion alleles like ***CYP2C19*36*** (complete deletion) and CYP2C19*37 (partial deletions involving upstream regions and…

[PMC12859152] Introduction
  mutant           …(PharmVar) 30 catalogues deletion alleles like CYP2C19*36 (complete deletion) and ***CYP2C19*37*** (partial deletions involving upstream regions and at least exon 1)…

[PMC12859152] Introduction
  mutant           …least exon 1) 20 , 31 , 32 . However, ***CYP2C19*37*** lacks in vivo phenotypic data and the allele is therefore…

[PMC12859152] Study overview
  mutant           …as NMa (normal metaboliser alleles); for CYP2C19 , NMa includes ***CYP2C19*1*** and *38 , and for CYP2D6 , NMa includes CYP2D6*1…

[PMC12859152] Study overview
  mutant           …(normal metaboliser alleles); for CYP2C19 , NMa includes CYP2C19*1 and ****38*** , and for CYP2D6 , NMa includes CYP2D6*1 , *2…

[PMC12859152] Study overview
  mutant           …are shown as pink dots. The five missense variants are: ***c.932C>T,*** c.911C>T, c.910T>C, c.901G>A, c.899C>G.…

[PMC12859152] Study overview
  mutant           …shown as pink dots. The five missense variants are: c.932C>T, ***c.911C>T,*** c.910T>C, c.901G>A, c.899C>G.…

[PMC12859152] Study overview
  mutant           …as pink dots. The five missense variants are: c.932C>T, c.911C>T, ***c.910T>C,*** c.901G>A, c.899C>G.…

[PMC12859152] Study overview
  mutant           …pink dots. The five missense variants are: c.932C>T, c.911C>T, c.910T>C, ***c.901G>A,*** c.899C>G.…

[PMC12859152] Study overview
  mutant           …dots. The five missense variants are: c.932C>T, c.911C>T, c.910T>C, c.901G>A, ***c.899C>G.*** …

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …was to characterise the functional consequences of the relatively understudied ***CYP2C19*37*** allele, which is defined as a partial gene deletion that…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …65 participants had at least one copy of the partial ***CYP2C19*37 deletion*** allele (chr10:94,737,567–94,799,352, GRCh38), and two participants had an intragenic deletion…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …exon 5 (chr10:94,774,141- 94,782,978, GRCh38). Based on long-read sequencing, all ***CYP2C19*37*** alleles shared identical breakpoints, confirming that they represent the same…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …individuals and was submitted to PharmVar for review. Since the ***CYP2C19*37*** allele is defined as a partial deletion spanning over exon…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …defined as a partial deletion spanning over exon 1, the ***exon 2-5*** deletion was designated a new star allele - CYP2C19*42 .…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …exon 2-5 deletion was designated a new star allele - ***CYP2C19*42*** . Among these 67 participants, two individuals were homozygous for…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …67 participants, two individuals were homozygous for partial deletions ( ***CYP2C19*37/*37*** ) and exhibited a clear PM phenotype when compared to…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …) and exhibited a clear PM phenotype when compared to ***CYP2C19*1/*1*** (β = 2.5, 95% CI = 1.7–3.4, P = 1.2…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …with the phenotype typically observed in individuals with the nonfunctional ***CYP2C19*2/*2*** diplotype (no significant difference in metabolic ratio, P = 0.498).…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …(no significant difference in metabolic ratio, P = 0.498). When ***CYP2C19*37*** or CYP2C19*42 was paired with a fully functional allele (e.g.,…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …difference in metabolic ratio, P = 0.498). When CYP2C19*37 or ***CYP2C19*42*** was paired with a fully functional allele (e.g., CYP2C19*1 or…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …or CYP2C19*42 was paired with a fully functional allele (e.g., ***CYP2C19*1*** or *38 ), participants typically exhibited an IM phenotype (β…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …P = 0.011). These data provide robust evidence that the ***CYP2C19*37*** allele results in loss of function and suggest that the…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …in loss of function and suggest that the shorter deletion ***CYP2C19*42*** spanning over exon 2 to exon 5 appears to have…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …metabolism. a Two distinct CYP2C19 deletions of differing lengths ( ***CYP2C19*37*** : del_exon1-5 and CYP2C19*42 : del_exon2-5) were identified in 67…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …Two distinct CYP2C19 deletions of differing lengths ( CYP2C19*37 : ***del_exon1-5*** and CYP2C19*42 : del_exon2-5) were identified in 67 individuals. The…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …CYP2C19 deletions of differing lengths ( CYP2C19*37 : del_exon1-5 and ***CYP2C19*42*** : del_exon2-5) were identified in 67 individuals. The schematic illustrates…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …of differing lengths ( CYP2C19*37 : del_exon1-5 and CYP2C19*42 : ***del_exon2-5)*** were identified in 67 individuals. The schematic illustrates the CYP2C19…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …Ensembl) and the genomic locations of the two deletions. The ***CYP2C19*37*** deletion extends upstream of exon 1 into the intergenic region…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …the intergenic region between CYP2C18 and CYP2C19 , whereas the ***CYP2C19*42*** deletion is an intragenic deletion retaining exon 1. Deletion intervals…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …retaining exon 1. Deletion intervals are indicated in light blue ***(del_exon1-5)*** and pink (del_exon2-5). b The plot shows the omeprazole log-transformed…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …Deletion intervals are indicated in light blue (del_exon1-5) and pink ***(del_exon2-5).*** b The plot shows the omeprazole log-transformed metabolic ratio in…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …of the variants were missense or nonfunctional, of which six ***(c.940C>A,*** c.932C>T, c.911C>T, c.910T>C, c.901G>A, c.899C>G) were missense and one frameshift…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …the variants were missense or nonfunctional, of which six (c.940C>A, ***c.932C>T,*** c.911C>T, c.910T>C, c.901G>A, c.899C>G) were missense and one frameshift (c.1450del),…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …variants were missense or nonfunctional, of which six (c.940C>A, c.932C>T, ***c.911C>T,*** c.910T>C, c.901G>A, c.899C>G) were missense and one frameshift (c.1450del), involving…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …were missense or nonfunctional, of which six (c.940C>A, c.932C>T, c.911C>T, ***c.910T>C,*** c.901G>A, c.899C>G) were missense and one frameshift (c.1450del), involving a…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …missense or nonfunctional, of which six (c.940C>A, c.932C>T, c.911C>T, c.910T>C, ***c.901G>A,*** c.899C>G) were missense and one frameshift (c.1450del), involving a total…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …or nonfunctional, of which six (c.940C>A, c.932C>T, c.911C>T, c.910T>C, c.901G>A, ***c.899C>G)*** were missense and one frameshift (c.1450del), involving a total of…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …c.932C>T, c.911C>T, c.910T>C, c.901G>A, c.899C>G) were missense and one frameshift ***(c.1450del),*** involving a total of five individuals (Supplementary Data 8 ).…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …). This included one novel missense variant in exon 6 ***(c.940C>A)*** found in two individuals (Supplementary Fig. 6 ), which had…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …assignment, both individuals with this variant were originally genotyped as ***CYP2D6*1/*1*** (no additional CYP2D6 variants within the gene region), and though…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …9 ). Three other individuals had a rare frameshift variant ***(c.1450del,*** rs200304972, gnomAD MAF MiddleEastern = 0.02%, MAF EUR = 0%).…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …diplotype had six of these seven variants, including the frameshift ***(c.1450del),*** all on the CYP2D6*68 allele within the CYP2D7 -derived sequence.…

[PMC12859152] Identification of novel  CYP2D6  variants

### Testing annotation of ~variants with OTAR3088 model

- Aware variant terms in text are being annotated with different labels, such as 'residue_name_number' at present

In [4]:
otar_model = "Mardiyyah/variant_tapt_freeze_llrd_LR_5e"
tokenizer, model, id2label = load_model(model_name = otar_model)

all_results: dict[str, list[SectionResult]] = {}
context_words = 10
lookback = None # De-duplicates sentences

for pmcid in papers:
    xml_out = get_epmc_full_text(pmcid=pmcid)
    if xml_out is None:
        continue
    parsed  = parse_epmc_xml(pmcid=pmcid, xml_text=xml_out)
    results = run_ner_pipeline(parsed, model=model, tokenizer=tokenizer, id2label=id2label)
    all_results[pmcid] = results
    # Preview annotations
    for sec in results:
        if sec.entities:
            for ent in sec.entities:
                context = get_context(sec.text, ent, window=context_words)
                if context == lookback:
                    continue
                if ent.label in ['mutant', 'residue_name_number']:
                    print(f"\n[{pmcid}] {sec.heading or 'Body'}")
                    print(f"  {ent.label:15s}  {context}")
                lookback = context

[PMC12713268] Genetic testing
  residue_name_number  …Collectively, these kits target BRCA1 c.68_69delAG (185delAG), c.181T > G ***(p.Cys61Gly),*** c.1961del (2080delA), c.3700_3704del (3819del5), c.3756_3759del (3875del4), c.4035delA (4153delA), c.5266dupC (5382insC),…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …Colon Cancer MLH1 Missense ( NM_000249.4 ):c.350 C > T ***p.(Thr117Met)*** Pathogenic rs63750781 47.3% No P2 Male/66 Colon Cancer MLH1 Missense…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …Colon Cancer MLH1 Missense ( NM_000249.4 ):c.244 A > G ***p.(Thr82Ala)*** Pathogenic rs587778998 46.1% No P3 Female/48 Right Colon Cancer PMS2…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …MLH1 Missense ( NM_000249.4 ):c.244 A > G p.(Thr82Ala) Pathogenic ***rs587778998*** 46.1% No P3 Female/48 Right Colon Cancer PMS2 Nonsense (…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …Colon Cancer PMS2 Nonsense ( NM_000535.7 ):c.1297 A > T ***p.(Lys433Ter)*** Pathogenic Novel 46.3% No P4 Male/37 Colon Cancer MSH6 Frameshift…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …No P4 Male/37 Colon Cancer MSH6 Frameshift ( NM_000179.3 ):c.2177delT ***p.(Phe726SerfsTer10)*** Pathogenic Novel 47% No FAP P5 Male/48 Polyps and cancer…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …the colon APC Nonsense ( NM_000038.6 ):c.637 C > T ***p.(Arg213Ter)*** Pathogenic rs587781392 45.9% Yes (Paternal) P6 Female/25 Polyps in the…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …APC Nonsense ( NM_000038.6 ):c.637 C > T p.(Arg213Ter) Pathogenic ***rs587781392*** 45.9% Yes (Paternal) P6 Female/25 Polyps in the colon and…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …the stomach APC Nonsense ( NM_000038.6 ):c.694 C > T ***p.(Arg232Ter)*** Pathogenic rs397515734 45% No Patients with unknown inherited syndrome predisposing…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …APC Nonsense ( NM_000038.6 ):c.694 C > T p.(Arg232Ter) Pathogenic ***rs397515734*** 45% No Patients with unknown inherited syndrome predisposing to CRC…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …Familial Colon Cancer CHEK2 Missense ( NM_007194.4 ):c.549G > C ***p.(Leu183Phe)*** Likely Pathogenic rs745646057 46.5% No P9 Male/69 Colon Cancer ATM…

[PMC12465344] Pathogenic and likely pathogenic variants
  residue_name_number  …No P10 Female/49 Colon Cancer MUC16 Frameshift ( NM_024690.2 ):c.37524del ***p.(Thr12509ProfsTer47)*** Likely Pathogenic Novel 47.9% No dbSNP Single-nucleotide polymorphism database, HGVS…

[PMC12465344] Molecular analysis of patients with Lynch syndrome
  residue_name_number  …in MLH1 were identified in Patients P1 and P2 as ***p.(Thr117Met)*** [ 17 ] and p.(Thr82Ala) [ 18 ], respectively. Patient…

[PMC12465344] Molecular analysis of patients with Lynch syndrome
  residue_name_number  …Patients P1 and P2 as p.(Thr117Met) [ 17 ] and ***p.(Thr82Ala)*** [ 18 ], respectively. Patient P3 carried a novel pathogenic…

[PMC12465344] Molecular analysis of patients with Lynch syndrome
  residue_name_number  …], respectively. Patient P3 carried a novel pathogenic nonsense variant, ***p.(Lys433Ter),*** in the PMS2 gene. Similarly, Patient P4 harbored a novel…

[PMC12465344] Molecular analysis of patients with Lynch syndrome
  residue_name_number  …gene. Similarly, Patient P4 harbored a novel pathogenic frameshift variant, ***p.(Phe726SerfsTer10),*** in the MSH6 gene. All patients developed colorectal cancer, with…

[PMC12465344] Molecular analysis of patients with polyposis
  residue_name_number  …of familial adenomatous polyposis. Patient P5 harbored a nonsense variant ***p.(Arg213Ter),*** whereas Patient P6 exhibited p.(Arg232Ter), both of which are well…

[PMC12465344] Molecular analysis of patients with polyposis
  residue_name_number  …P5 harbored a nonsense variant p.(Arg213Ter), whereas Patient P6 exhibited ***p.(Arg232Ter),*** both of which are well documented as pathogenic [ 19…

[PMC12465344] Molecular analysis of patients with polyposis
  residue_name_number  …, 20 ]. Additionally, a single variant of uncertain significance, ***p.(Ile223Val),*** in the MUTYH gene was detected in one patient (P11)…

[PMC12465344] Molecular analysis of patients with an unknown inherited syndrome predisposing to CRC
  residue_name_number  …familial colon and pancreas cancers. A likely pathogenic missense variant ***p.(Leu183Phe),*** in CHEK2 was identified in P8, a patient with familial…

[PMC12465344] Molecular analysis of patients with an unknown inherited syndrome predisposing to CRC
  residue_name_number  …inherited cancer risk. A likely pathogenic novel frameshift germline variant, ***p.(Thr12509ProfsTer47),*** in MUC16 was identified in Patient P10, who presented with…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …Colon Cancer MUTYH Missense ( NM_001128425.2 ):c.667 A > G ***(p.Ile223Val)*** VUS rs200965879 46.1% No Patients with unknown inherited syndromes predisposing…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …big polyp XRCC3 Missense ( NM_001100119.2 ):c.964 C > T ***p.(His322Tyr)*** VUS Novel 47% No P14 Male/68 Stomach and Colon Cancers…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …Colon Cancers PALB2 Missense ( NM_024675.4 ):c.3306 C > G ***p.(Ser1102Arg)*** VUS rs515726112 41.9% No P15 Male/65 Polyps in the Sigmoid…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …Sigmoid Colon ATM Missense ( NM_000051.4 ):c.2384 C > T ***p.(Pro795Leu)*** VUS Novel 46.3% No P16 Female/64 Polyps in the colon…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …in the colon SYNE1 Missense ( NM_033071.4 ):c.8102G > A ***p.(Ser2701Asn)*** VUS Novel 44.9% No P17 Female/76 Colon Adeno -carcinoma RAD51D…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …Adeno -carcinoma RAD51D Missense ( NM_002878.4 ):c.412 A > C ***p.(Asn138His)*** VUS rs141690729 46.6% Yes (Maternal) P18 Female/76 Breast and Colon…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …Colon Cancer NF1 Missense ( NM_000267.3 ):c.584 A > G ***p.(Lys195Arg)*** VUS rs587778552 43.5% No P19 Female/63 Colon Cancer ATR Missense…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …Colon Cancer ATR Missense ( NM_001184.4 ):c.4405 A > G ***p.(Thr1469Ala)*** VUS rs78895258 46% No P20 Male/47 Operated Colon Cancer ABRAXAS1…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …Colon Cancer ABRAXAS1 Missense ( NM_139076.3 ):c.727 C > G ***p.(Leu243Val)*** VUS rs755187051 45.5% No P21 Female/39 Colon cancer and Ovarian…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …and Ovarian Metastasis ERBB2 Missense ( NM_004448.4 ):c.3565G > C ***p.(Gly1189Arg)*** VUS Novel 46.7% No P22 Female/66 Rectum and Ovarian Cancers…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …Ovarian Cancers FGFR1 Missense ( NM_023110.3 ):c.386 A > C ***p.(Asp129Ala)*** VUS rs765615419 47% No P23 Female/78 Uterus and Rectum Cancers…

[PMC12465344] Variants of uncertain significance (VUS)
  residue_name_number  …Rectum Cancers CHEK2 Missense ( NM_007194.4 ):c.906 A > C ***p.(Glu302Asp)*** VUS rs587780190 45.6% No dbSNP Single-nucleotide polymorphism database, HGVS Human…

[PMC12465344] Discussion
  residue_name_number  …Li–Fraumeni syndrome [ 31 ]. The specific variants 1100delC and ***I157T,*** have been identified as risk variants for colorectal cancer syndromes,…

[PMC12465344] Discussion
  residue_name_number  …VUS were identified in the XRCC3 (c.964 C > T; ***p.(His322Tyr)),*** ATM (c.2384 C > T; p.(Pro795Leu)), and SYNE1 (c.8102G >…

[PMC12465344] Discussion
  residue_name_number  …(c.964 C > T; p.(His322Tyr)), ATM (c.2384 C > T; ***p.(Pro795Leu)),*** and SYNE1 (c.8102G > A; p.(Ser2701Asn)) genes in three families…

[PMC12465344] Discussion
  residue_name_number  …(c.2384 C > T; p.(Pro795Leu)), and SYNE1 (c.8102G > A; ***p.(Ser2701Asn))*** genes in three families with colonic polyps. To our knowledge,…

[PMC12859152] Study overview
  mutant           …*38 , and for CYP2D6 , NMa includes CYP2D6*1 , ****2*** , *33 , and *35 . Genotypes are coloured by…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …65 participants had at least one copy of the partial ***CYP2C19*37*** deletion allele (chr10:94,737,567–94,799,352, GRCh38), and two participants had an intragenic…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …exon 5 (chr10:94,774,141- 94,782,978, GRCh38). Based on long-read sequencing, all ***CYP2C19*37*** alleles shared identical breakpoints, confirming that they represent the same…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …exon 2-5 deletion was designated a new star allele - ***CYP2C19*42*** . Among these 67 participants, two individuals were homozygous for…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …) and exhibited a clear PM phenotype when compared to ***CYP2C19*1/*1*** (β = 2.5, 95% CI = 1.7–3.4, P = 1.2…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …difference in metabolic ratio, P = 0.498). When CYP2C19*37 or ***CYP2C19*42*** was paired with a fully functional allele (e.g., CYP2C19*1 or…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …or CYP2C19*42 was paired with a fully functional allele (e.g., ***CYP2C19*1*** or *38 ), participants typically exhibited an IM phenotype (β…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …was paired with a fully functional allele (e.g., CYP2C19*1 or ****38*** ), participants typically exhibited an IM phenotype (β = 0.41,…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …Two distinct CYP2C19 deletions of differing lengths ( CYP2C19*37 : ***del_exon1-5*** and CYP2C19*42 : del_exon2-5) were identified in 67 individuals. The…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …of differing lengths ( CYP2C19*37 : del_exon1-5 and CYP2C19*42 : ***del_exon2-5)*** were identified in 67 individuals. The schematic illustrates the CYP2C19…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …retaining exon 1. Deletion intervals are indicated in light blue ***(del_exon1-5)*** and pink (del_exon2-5). b The plot shows the omeprazole log-transformed…

[PMC12859152] Functional characterisation of  CYP2C19  deletions
  mutant           …Deletion intervals are indicated in light blue (del_exon1-5) and pink ***(del_exon2-5).*** b The plot shows the omeprazole log-transformed metabolic ratio in…

[PMC12859152] Identification of novel  CYP2D6  variants
  residue_name_number  …c.932C>T, c.911C>T, c.910T>C, c.901G>A, c.899C>G) were missense and one frameshift ***(c.1450del),*** involving a total of five individuals (Supplementary Data 8 ).…

[PMC12859152] Identification of novel  CYP2D6  variants
  residue_name_number  …9 ). Three other individuals had a rare frameshift variant ***(c.1450del,*** rs200304972, gnomAD MAF MiddleEastern = 0.02%, MAF EUR = 0%).…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …sequence. The two other individuals with this variant (c.1450del) had ***CYP2D6*4/*68 + *4*** and *5/*68 + *4 diplotypes. In all three individuals, the…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …presence of CYP2D7 sequence downstream of intron 1 in all ***CYP2D6*68*** hybrids, consistent with the canonical CYP2D6/CYP2D7 hybrid structure. Given that…

[PMC12859152] Identification of novel  CYP2D6  variants
  residue_name_number  …enzyme activity. Three individuals had the rare CYP2D6*124 allele (c.1184_1185del, ***rs757396767,*** MAF EUR = 0.01%, Supplementary Fig. 6 ). Two CYP2D6…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …Supplementary Data 9 ), with higher metabolic ratios than CYP2D6 ***NMa/*41*** ( P = 0.02) but significantly different from PMs with…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …the metabolic ratio in the single individual with a CYP2D6 ***NMa/*124*** diplotype also suggests that CYP2D6*124 may not confer a complete…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …= 1.0–2.5, P = 8.9 × 10 −6 ) and ****41*** (β = 1.4, 95% CI = 0.71–2.1, P = 1.6…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …identification of hybrid alleles of CYP2D6-2D7 . When comparing CYP2D6 ***NMa/*68*** + *4 to CYP2D6 NMa/*4 , no significant difference in…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …CYP2D6-2D7 . When comparing CYP2D6 NMa/*68 + *4 to CYP2D6 ***NMa/*4*** , no significant difference in metabolic ratio was observed (P…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …(P = 0.30). In addition, individuals having the hybrid allele ***CYP2D6*68 + *4*** in combination with a CYP2D6*4 allele ( CYP2D6*4/*68 + *4…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …CYP2D6*68 + *4 in combination with a CYP2D6*4 allele ( ***CYP2D6*4/*68*** + *4 ) exhibited a PM phenotype (β = 7.1,…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …CYP2D6*68 + *4 in combination with a CYP2D6*4 allele ( ***CYP2D6*4/*68 + *4*** ) exhibited a PM phenotype (β = 7.1, 95% CI…

[PMC12859152] Identification of novel  CYP2D6  variants
  mutant           …CYP2D6/2D7 hybrid allele and providing in vivo evidence that the ***CYP2D6*68 + *4*** configuration results in no enzymatic activity.…

[PMC12859152] Discussion
  mutant           …CYP2C19 and CYP2D6 , including partial deletions in CYP2C19 ( ****37*** and *42 ) that have not been functionally validated yet…

[PMC12859152] Discussion
  mutant           …CYP2D6 , including partial deletions in CYP2C19 ( *37 and ****42*** ) that have not been functionally validated yet 20 .…

[PMC12859152] Discussion
  residue_name_number  …results, which showed 40% reduced CYP2D6 activity for this variant ***(p.Leu314Met)*** 42 . Due to the small sample size, our analysis…

[PMC12859152] Discussion
  residue_name_number  …variant. At the time of recruitment, the nonfunctional CYP2D6 variant ***rs757396767*** (c.1184_1185del), a two-base pair deletion in exon 8 leading to…

[PMC12859152] Discussion
  residue_name_number  …two-base pair deletion in exon 8 leading to a frameshift ***(L395fs),*** was considered novel and unclassified as part of any star…

[PMC12859152] Discussion
  mutant           …CYP2D6*1/*41 , thereby supporting a classification of decreased function for ***CYP2D6*124*** . However, the CYP2D6*41/*124 diplotype did not result in a…

[PMC12859152] Discussion
  mutant           …phenotype CYP2D6*4/*4 . For the one individual with a CYP2D6 ***NMa/*124*** diplotype, the observed metabolic ratio also suggested a partial reduction…

[PMC12859152] Discussion
  mutant           …describing substantial variability in the functional impact of CYP2D6*9 and ****41*** , reflecting the complex and context-dependent nature of decreased function…

[PMC12859152] Discussion
  mutant           …our study, the individuals with CYP2D6*41 ( NMa/*41 ) and ***CYP2D6*9*** ( NMa/*9 ), displayed metabolic ratios at the lower end…

[PMC12859152] Discussion
  mutant           …the individuals with CYP2D6*41 ( NMa/*41 ) and CYP2D6*9 ( ***NMa/*9*** ), displayed metabolic ratios at the lower end of the…

[PMC12859152] Discussion
  mutant           …not observe any differences in the metabolic ratio between CYP2D6 ***NMa/*68*** + *4 and CYP2D6 NMa/*4 , suggesting that failure to…

[PMC12859152] Discussion
  mutant           …the metabolic ratio between CYP2D6 NMa/*68 + *4 and CYP2D6 ***NMa/*4*** , suggesting that failure to detect the hybrid allele may…

[PMC12859152] Discussion
  mutant           …alter the determined metabolic phenotype. Only one individual with the ***CYP2D6*13 + *2*** allele ( NMa/*13 + *2 diplotype) participated in our study…

[PMC12859152] Discussion
  mutant           …Only one individual with the CYP2D6*13 + *2 allele ( ***NMa/*13*** + *2 diplotype) participated in our study and displayed a…

[PMC12859152] Discussion
  mutant           …Consistent with CPIC, PharmVar, and previous reports, CYP2D6*68 and the ****68 + *4*** tandem are nonfunctional. Our long-read data confirm these structures and…

[PMC12859152] Discussion
  mutant           …we did not identify any individuals with the novel haplotype ***(*1/*1*** + c.940 C > A ) in combination with a…

[PMC12859152] Discussion
  mutant           …we did not identify any individuals with the novel haplotype ***(*1/*1 + c.940 C > A*** ) in combination with a nonfunctional allele in our cohort,…

[PMC12859152] Discussion
  mutant           …which may refine phenotype predictions. Recent work on CYP2D6*17 and ****29*** demonstrated substrate-dependent activity for risperidone metabolism 47 , illustrating the…

[PMC12859152] Variant detection and participant selection
  mutant           …reference allele, increased or no function alleles of CYP2C19 ( ****1*** , *2 , *17 ) or CYP2D6 (*1, *4) .…

[PMC12859152] Variant detection and participant selection
  mutant           …increased or no function alleles of CYP2C19 ( *1 , ****2*** , *17 ) or CYP2D6 (*1, *4) . Eligible participants…

[PMC12859152] Variant detection and participant selection
  mutant           …no function alleles of CYP2C19 ( *1 , *2 , ****17*** ) or CYP2D6 (*1, *4) . Eligible participants were adults…

[PMC12859152] Variant detection and participant selection
  mutant           …CYP2C19 ( *1 , *2 , *17 ) or CYP2D6 ***(*1,*** *4) . Eligible participants were adults (age ≥ 18 years,…

[PMC12859152] Variant detection and participant selection
  mutant           …( *1 , *2 , *17 ) or CYP2D6 (*1, ****4)*** . Eligible participants were adults (age ≥ 18 years, no…

[PMC12859152] Measures of enzyme activity
  mutant           …log-linear trapezoidal rule (linear-up log-down method) with the R package ***pkr.*** The metabolic ratios were computed as the AUC of the…

[PMC12859152] CYP2C19  deletion frequency in the Estonian Biobank
  mutant           …frequency of the CYP2C19 partial gene deletion ( CYP2C19*37 or ***CYP2C19*42*** ) in EstBB, individuals with deletion were identified using PennCNV…

[PMC12859152] Post-recruitment long-read sequencing of participants
  mutant           …the full coding sequence. The well-known upstream regulatory variant CYP2C19*17 ***(c.-806C>T,*** rs12248560; chr10:94,761,900) was added to the analysis. For CYP2D6 ,…

[PMC12859152] Post-recruitment long-read sequencing of participants
  residue_name_number  …full coding sequence. The well-known upstream regulatory variant CYP2C19*17 (c.-806C>T, ***rs12248560;*** chr10:94,761,900) was added to the analysis. For CYP2D6 , we…

### Testing geneprotein model
- Due to limited coverage of ePMC annotations API, trying out BERT models trained to annotate geneprotein

In [ ]:
from transformers import pipeline

# BENT-PubMedBERT
# Labels: gene, protein
ner_gene = pipeline(
    "ner",
    model="pruas/BENT-PubMedBERT-NER-Gene",
    aggregation_strategy="simple"   # merges subword tokens into full spans
)

text = """
Pathogenic variants in MLH1 were identified in three patients. 
A frameshift variant in MSH6 was found in P4. Two germline variants 
in APC were detected, and a variant in MUTYH was confirmed in P11 
diagnosed with MUTYH-associated polyposis. Additionally, a splice variant 
in FANCC was detected and a missense variant in CHEK2 was identified.
"""

results = model_pipe(text)
for ent in results:
    print(f"  [{ent['start']:4d}:{ent['end']:4d}]  {ent['entity_group']:12s}  {ent['score']:.3f}  {ent['word']!r}")

Device set to use mps:0

<class 'list'>
  [  24:  28]  B             0.991  'mlh1'
  [  89:  93]  B             0.963  'msh6'
  [ 137: 140]  B             0.963  'apc'
  [ 173: 178]  B             0.872  'mutyh'
  [ 279: 284]  B             0.907  'fancc'
  [ 324: 329]  B             0.982  'chek2'

/Users/withers/GitProjects/OTAR3088/ner-model/lib/python3.10/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

### Comparison of models

In [ ]:
import pandas as pd

def spans_overlap(a: Entity, b: Entity) -> bool:
    """True if two entity spans overlap at all."""
    return a.start < b.end and b.start < a.end

def compare_models(section_results_a: list[SectionResult],
                   section_results_b: list[SectionResult],
                   model_a_name: str = "Model A",
                   model_b_name: str = "Model B",
                   context_words: int = 5,) -> pd.DataFrame:
    """SectionResult: pmcid, heading (section heading), text, entities: list[Entity]"""

    rows = []
    b_index = {(s.pmcid, s.heading): s.entities for s in section_results_b}
    for sect_a in section_results_a:
        key = (sect_a.pmcid, sect_a.heading)
        b_entities = b_index.get(key, [])
        matched_b: set[int] = set()
        for ent_a in sect_a.entities:
            context_a = get_context(sect_a.text, ent_a, window=context_words)
            match_b = None
            for i, ent_b in enumerate(b_entities):
                if i not in matched_b and spans_overlap(ent_a, ent_b):
                    match_b = (i, ent_b)
                    break
            if match_b:
                idx_b, ent_b = match_b
                matched_b.add(idx_b)
                context_b = get_context(sect_a.text, ent_b, window=context_words)
                rows.append({
                    "pmcid":                       sect_a.pmcid,
                    "section":                     sect_a.heading,
                    "span_text":                   ent_a.text,
                    f"{model_a_name}_label":       ent_a.label,
                    f"{model_a_name}_context":     context_a,          # A context
                    f"{model_b_name}_label":       ent_b.label,
                    f"{model_b_name}_context":     context_b,          # B context
                    "label_agreement":             "AGREE" if ent_a.label == ent_b.label else "DISAGREE",
                    "found_by":                    "both",
                })
            else:
                rows.append({
                    "pmcid":                       sect_a.pmcid,
                    "section":                     sect_a.heading,
                    "span_text":                   ent_a.text,
                    f"{model_a_name}_label":       ent_a.label,
                    f"{model_a_name}_context":     context_a,          # A context
                    f"{model_b_name}_label":       "—",
                    f"{model_b_name}_context":     "—",            # B missed it
                    "label_agreement":             "—",
                    "found_by":                    model_a_name,
                })
        for i, ent_b in enumerate(b_entities):
            if i not in matched_b:
                context_b = get_context(sect_a.text, ent_b, window=context_words)
                rows.append({
                    "pmcid":                       sect_a.pmcid,
                    "section":                     sect_a.heading,
                    "span_text":                   ent_b.text,
                    f"{model_a_name}_label":       "—",
                    f"{model_a_name}_context":     "—",            # A missed it
                    f"{model_b_name}_label":       ent_b.label,
                    f"{model_b_name}_context":     context_b,          # B context
                    "label_agreement":             "—",
                    "found_by":                    model_b_name,
                })
    return pd.DataFrame(rows)

In [ ]:
papers = ["PMC7334197", "PMC12713268", "PMC12465344", "PMC12859152", "PMC12874668"]
# Parse: pmcid -> ParsedPaper
all_parsed: dict[str, ParsedPaper] = {}
for pmcid in papers:
    xml_out = get_epmc_full_text(pmcid=pmcid)
    if xml_out is None:
        continue
    all_parsed[pmcid] = parse_epmc_xml(pmcid=pmcid, xml_text=xml_out)

pdbe_model = "PDBEurope/BiomedNLP-PubMedBERT-ProteinStructure-NER-v3.1"
otar_model = "Mardiyyah/variant_tapt_freeze_llrd_LR_5e"
# Run pipelines separately with each model
tokenizer, model, id2label = load_model(pdbe_model)
results_a = {pmcid: run_ner_pipeline(parsed, tokenizer, model, id2label) for pmcid, parsed in all_parsed.items()}
tokenizer, model, id2label = load_model(otar_model)
results_b = {pmcid: run_ner_pipeline(parsed, tokenizer, model, id2label) for pmcid, parsed in all_parsed.items()}

# Flatten results to lists
flat_a = [sec for secs in results_a.values() for sec in secs]
flat_b = [sec for secs in results_b.values() for sec in secs]
df_comp = compare_models(flat_a, flat_b, model_a_name="PubMed-Mutant-BERT", model_b_name="OTAR-Variant-BERT", context_words=10)

# ── Summary views ──────────────────────────────────────────────────────────────
# Full comparison table
display(df_comp)
df_comp.to_csv("./output/genevar_outputs/df_comp.tsv", sep="\t")
# Agreement rate among spans found by both
both = df_comp[df_comp["found_by"] == "both"]
agree_rate = (both["label_agreement"] == "AGREE").mean()
print(f"\nLabel agreement (overlapping spans): {agree_rate:.1%}")
# What each model found exclusively
print(f"\nOnly by PubMed-Mutant-BERT:  {(df_comp['found_by']=='PubMed-Mutant-BERT').sum()} entities")
print(f"Only by OTAR-Variant-BERT:     {(df_comp['found_by']=='OTAR-Variant-BERT').sum()} entities")
print(f"Found by both:           {len(both)} entities")
# Breakdown by label
display(
    df_comp.groupby(["found_by", "PubMed-Mutant-BERT_label", "OTAR-Variant-BERT_label"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)

/Users/withers/GitProjects/OTAR3088/ner-model/lib/python3.10/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

,pmcid,section,span_text,PubMed-Mutant-BERT_label,PubMed-Mutant-BERT_context,OTAR-Variant-BERT_label,OTAR-Variant-BERT_context,label_agreement,found_by
0,PMC7334197,Abstract,human,species,"…describe the aggregation of 125,748 exomes an...",species,"…describe the aggregation of 125,748 exomes an...",AGREE,both
1,PMC7334197,Abstract,human,species,…by sequencing and annotation errors. Using an...,species,…by sequencing and annotation errors. Using an...,AGREE,both
2,PMC7334197,Abstract,human,species,…Using an improved model of human mutation rat...,species,…Using an improved model of human mutation rat...,AGREE,both
3,PMC7334197,Abstract,human,species,…validate this classification using data from ...,species,…validate this classification using data from ...,AGREE,both
4,PMC7334197,Abstract,whole-exome,experimental_method,…rare diseases. A catalogue of predicted loss-...,—,—,—,PubMed-Mutant-BERT
...,...,...,...,...,...,...,...,...,...
2819,PMC12874668,Discussion,Xp,—,—,gene,…translocation of the Yp11.2 region (containin...,—,OTAR-Variant-BERT
2820,PMC12874668,Discussion,SOC,—,—,experimental_method,…pathway applicable to “unexplained adverse pr...,—,OTAR-Variant-BERT
2821,PMC12874668,Discussion,SR,—,—,experimental_method,…risk assessment and recommend preimplantation...,—,OTAR-Variant-BERT
2822,PMC12874668,Discussion,short arm,—,—,structure_element,…in sex chromosome analysis—when the Y chromos...,—,OTAR-Variant-BERT
2823,PMC12874668,Discussion,s,—,—,experimental_method,"…reproductive failures, expand their reproduct...",—,OTAR-Variant-BERT

Label agreement (overlapping spans): 81.6%

Only by PubMed-Mutant-BERT:  509 entities
Only by OTAR-Variant-BERT:     883 entities
Found by both:           1432 entities

              found_by PubMed-Mutant-BERT_label OTAR-Variant-BERT_label  count
55                both                  protein                 protein    419
40                both      experimental_method     experimental_method    347
12   OTAR-Variant-BERT                        —          residue_number    198
4    OTAR-Variant-BERT                        —                    gene    158
23  PubMed-Mutant-BERT                  protein                       —    137
..                 ...                      ...                     ...    ...
49                both                   mutant           protein_state      1
61                both            protein_state          residue_number      1
28  PubMed-Mutant-BERT           residue_number                       —      1
51                both                   mutant            residue_name      1
41                both      experimental_method                     ptm      1

[74 rows x 4 columns]

In [30]:
labels_of_interest = {"mutant", "residue_name_number"}
mask = (
    df_comp["PubMedBERT-NER_label"].isin(labels_of_interest) | df_comp["VariantBERT_label"].isin(labels_of_interest))
df_filtered = df_comp[mask]
df_filtered.to_csv("./output/genevar_outputs/varmodels_comparison.tsv", sep="\t")
display(df_filtered)

,pmcid,section,span_text,PubMedBERT-NER_label,PubMedBERT-NER_context,VariantBERT_label,VariantBERT_context,label_agreement,found_by
409,PMC12713268,Abstract,c.5266dup,mutant,…BRCA2 gene. The BRCA1 variant ***c.5266dup***...,residue_number,…BRCA2 gene. The BRCA1 variant ***c.5266dup***...,✗,both
475,PMC12713268,Genetic testing,Cys,mutant,"…c.68_69delAG (185delAG), c.181T > G ***(p.Cys...",residue_name_number,"…c.68_69delAG (185delAG), c.181T > G ***(p.Cys...",✗,both
476,PMC12713268,Genetic testing,61,mutant,"…c.68_69delAG (185delAG), c.181T > G ***(p.Cys...",ptm,"…c.68_69delAG (185delAG), c.181T > G ***(p.Cys...",✗,both
574,PMC12713268,Discussion,с.5266dup,mutant,…[ 22 ]. The variant ***с.5266dup*** is predom...,residue_number,…[ 22 ]. The variant ***с.5266dup*** is predom...,✗,both
575,PMC12713268,Discussion,c.4153del,mutant,"…is found in 57–68%, the ***c.4153del*** patho...",residue_number,"…is found in 57–68%, the ***c.4153del*** patho...",✗,both
...,...,...,...,...,...,...,...,...,...
2315,PMC12859152,CYP2C19 deletion frequency in the Estonian Bi...,CYP2C19*37,mutant,…CYP2C19 partial gene deletion ( ***CYP2C19*37...,protein,…CYP2C19 partial gene deletion ( ***CYP2C19*37...,✗,both
2316,PMC12859152,CYP2C19 deletion frequency in the Estonian Bi...,CYP2C19*42,mutant,…gene deletion ( CYP2C19*37 or ***CYP2C19*42**...,mutant,…gene deletion ( CYP2C19*37 or ***CYP2C19*42**...,✓,both
2396,PMC12859152,Post-recruitment long-read sequencing of parti...,c.-806C>T,mutant,…well-known upstream regulatory variant CYP2C1...,residue_name,…well-known upstream regulatory variant CYP2C1...,✗,both
2401,PMC12859152,Post-recruitment long-read sequencing of parti...,rs,gene,…upstream regulatory variant CYP2C19*17 (c.-80...,residue_name_number,…upstream regulatory variant CYP2C19*17 (c.-80...,✗,both
2421,PMC12859152,Post-recruitment long-read sequencing of parti...,c.,—,—,mutant,…well-known upstream regulatory variant CYP2C1...,—,VariantBERT

### Older early works around model testing

In [23]:
def filter_res(results: List[Tuple], filter: str):
    for res in results:
        text = res[0]
        tagged = res[1]
        filtered = [x["entity"] for x in tagged if x["type"] == filter]
        if len(filtered) > 0:
            print("- - - - - - Original text - - - - -")
            pprint([x for x in text.split(sep='. ')])
            print(f"- - Terms tagged of type '{filter}' - -")
            pprint(filtered)

filter_res(e, "mutant")

NameError: name 'e' is not defined

In [ ]:
for p in papers:
    e = run_model(input_text=p)

/Users/withers/GitProjects/OTAR3088/ner-model/lib/python3.10/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [ ]:
# Some gemini example sentences, these are more obvious examples of variants
protein_variant_sentences = [
    "Studies on the protein-protein interaction network revealed that the R175H variant of p53 dramatically alters its binding partners, shifting its function from a tumor suppressor to an oncogenic driver.",
    "The structural consequences of the E6V substitution in hemoglobin are profound, leading to the formation of rigid polymers that deform red blood cells into their characteristic sickle shape.",
    "The D90A mutation in superoxide dismutase 1 (SOD1) highlights the complexity of disease mechanisms, as its pathogenicity in familial ALS is not due to a loss of catalytic activity but rather to a gain of toxic function.",
    "The ΔF508 deletion in the CFTR protein prevents its proper folding, triggering the cell's quality control system to target the misfolded protein for destruction in the endoplasmic reticulum.",
    "Kinase inhibitors are now a standard therapy for melanoma patients with the V600E mutation in BRAF, which constitutively activates the downstream signaling cascade.",
    "The single amino acid change A67T in transthyretin increases its propensity to misfold and aggregate, forming amyloid fibrils that deposit in the heart and other tissues.",
    "The pathogenicity of the A223P variant in fibrillin-1 lies in its disruption of calcium-binding sites, which are critical for the formation of stable microfibrils in the extracellular matrix.",
    "Patients with familial chylomicronemia resulting from the S267L variant of lipoprotein lipase exhibit severely impaired lipid clearance due to the protein's reduced catalytic efficiency.",
    "The R117H amino acid substitution in Factor V makes it resistant to cleavage by activated protein C, a critical step in down-regulating blood coagulation.",
    "The P101S amino acid change in the prion protein (PrP) is a crucial determinant of disease pathology, as it favors the conversion of the normal PrP ($PrP^C$) into the disease-associated scrapie form ($PrP^{Sc}$).",
    "The E280A mutation in presenilin 1 alters the cleavage of the amyloid precursor protein (APP), leading to an overproduction of the highly aggregation-prone Aβ42 peptide.",
    "Achondroplasia is caused by a G380R variant in fibroblast growth factor receptor 3 (FGFR3), which leads to the constitutive activation of the receptor even in the absence of its ligand.",
    "The K456N variant of cardiac troponin I impairs the calcium-dependent regulation of myocardial contraction, which is the underlying cause of hypertrophic cardiomyopathy.",
    "The C278F substitution in fibroblast growth factor receptor 2 (FGFR2) is a well-known example of a gain-of-function mutation, leading to premature fusion of the cranial sutures.",
    "The C282Y variant in the HFE protein disrupts its interaction with the transferrin receptor, leading to a breakdown in the regulation of iron absorption.",
    "The p.L320P variant of lamin A/C causes dilated cardiomyopathy by compromising the structural integrity of the nuclear lamina and disrupting normal gene expression patterns.",
    "The S295C mutation in myotilin creates a new cysteine residue, which can form inappropriate disulfide bonds, leading to the formation of aggregates that interfere with muscle function.",
    "The R402Q variant in the ATP-binding cassette transporter A4 (ABCA4) disrupts its ability to transport retinoids, leading to the accumulation of toxic compounds in the retinal pigment epithelium.",
    "A study of familial ALS patients identified the H46R mutation in SOD1, which was shown to lead to a misfolding and aggregation of the protein that is toxic to motor neurons.",
    "The E258K mutation in lysosomal acid lipase is a clear example of a loss-of-function variant, as it severely impairs the protein's ability to hydrolyze cholesterol esters.",
    "Individuals homozygous for the M34T variant in connexin 26 (GJB2) often present with non-syndromic hearing loss due to the disruption of gap junction function in the inner ear.",
    "Congenital contractural arachnodactyly is associated with the K197R mutation in fibrillin-2, a protein crucial for elastic fiber formation in connective tissues.",
    "The L268P mutation in type II collagen (COL2A1) results in a protein with impaired triple helix formation, leading to the skeletal abnormalities characteristic of Stickler syndrome.",
    "The P1213L variant in dynein heavy chain 1 (DYNC1H1) compromises the protein's motor function, resulting in defects in retrograde axonal transport that cause spinal muscular atrophy.",
    "The R782W mutation in α₁-antitrypsin (SERPINA1) results in a misfolded protein that is trapped in the liver, leading to a lack of circulating α₁-antitrypsin in the lungs.",
    "The R136Q amino acid substitution in ubiquitin carboxyl-terminal hydrolase L1 (UCHL1) affects its deubiquitinating activity, which may contribute to the accumulation of protein aggregates observed in Parkinson's disease.",
    "The P270S variant in glucocerebrosidase (GBA1) has been shown to reduce the enzyme's activity, which is a known risk factor for Parkinson's disease.",
    "The A30P mutation in α-synuclein is a rare but well-documented cause of familial Parkinson's disease, as it promotes the formation of neurotoxic fibrils and Lewy bodies.",
    "The R46L variant in proprotein convertase subtilisin/kexin type 9 (PCSK9) is a functional polymorphism that reduces the protein's ability to degrade LDL receptors, leading to lower levels of circulating LDL cholesterol.",
    "The A152T variant in the protein tau (MAPT) is a known risk factor for frontotemporal dementia, as it enhances the aggregation and misfolding of the protein."
]

In [ ]:
# Gemini mimicking descriptions of paper results, for protein variants then non-coding genetic variants to see what happens
protein_variant_sentences_experimental_results = [
    "Circular dichroism spectroscopy of the R175H p53 variant revealed a significant decrease in α-helical content compared to the wild-type protein, indicating a loss of structural integrity.",
    "In our gel electrophoresis assays, the E6V hemoglobin variant showed a distinct band shift in non-denaturing conditions, consistent with polymer formation under deoxygenated states.",
    "Immunoblot analysis of cells expressing the D90A SOD1 variant demonstrated a marked increase in detergent-insoluble protein, suggesting a propensity for aggregation.",
    "Western blot analysis of the ΔF508 CFTR variant showed a complete absence of the mature, fully glycosylated band, confirming that the protein is not trafficked to the cell surface.",
    "In vitro kinase assays confirmed a 500-fold increase in the phosphorylation of ERK and MEK substrates when using the V600E BRAF variant, demonstrating constitutive activation.",
    "Fluorescence microscopy with Thioflavin S staining revealed abundant amyloid deposits in cardiac tissue sections from mice expressing the A67T transthyretin variant.",
    "Our surface plasmon resonance (SPR) data demonstrated that the A223P fibrillin-1 variant has a significantly reduced binding affinity for calcium ions (Kd = 450 nM vs 50 nM for WT).",
    "Lipolysis assays using the S267L lipoprotein lipase variant showed only 15% of the catalytic activity observed with the wild-type enzyme.",
    "Coagulation assays of plasma containing the R117H Factor V variant showed a 12-fold increase in clotting time after the addition of activated protein C, confirming its resistance to inactivation.",
    "Real-time quaking-induced conversion (RT-QuIC) assays demonstrated that the P101S prion protein variant seeded the rapid formation of fibrils at a concentration 100-fold lower than the wild-type protein.",
    "Cell-free cleavage assays confirmed that the E280A presenilin 1 variant preferentially generated the highly amyloidogenic Aβ42 peptide over the Aβ40 peptide.",
    "Dual-luciferase reporter assays confirmed a 20-fold increase in STAT3 signaling in cells expressing the G380R FGFR3 variant, even in the absence of exogenous FGF ligand.",
    "Calcium-sensitizing assays on skinned cardiac muscle fibers revealed that the K456N troponin I variant increased the calcium sensitivity of force generation by 2.5-fold.",
    "Immunofluorescence staining revealed that the C278F FGFR2 variant localized to the cell membrane at a higher density and for a longer duration than the wild-type protein.",
    "In our iron uptake experiments, cells expressing the C282Y HFE variant failed to show the characteristic down-regulation of transferrin receptor expression in response to high iron levels.",
    "Immunoblotting of nuclear fractions showed a fragmented lamin A/C network in cells from patients with the p.L320P variant, indicating a loss of nuclear integrity.",
    "Pull-down assays with a cysteine-reactive probe demonstrated that the S295C myotilin mutation forms intermolecular disulfide bonds, leading to the formation of high-molecular-weight aggregates.",
    "Liposome-based transport assays using the R402Q ABCA4 variant showed a 90% reduction in the translocation of all-trans-retinal across the membrane.",
    "Immunohistochemistry of spinal cord sections from transgenic mice expressing the H46R SOD1 variant revealed extensive intracellular inclusions in motor neurons, which were immunoreactive for ubiquitin.",
    "In vitro enzyme kinetics demonstrated that the E258K lysosomal acid lipase variant had a Vmax that was less than 5% of the wild-type enzyme, confirming a severe loss-of-function.",
    "Dye-transfer assays showed a complete failure of Lucifer yellow transfer between cells expressing the M34T connexin 26 variant, indicating a loss of gap junction function.",
    "Atomic force microscopy of extracellular matrix fibers from cells expressing the K197R fibrillin-2 variant revealed an aberrant, disorganized microfibril network.",
    "A triple helix formation assay using purified L268P collagen type II demonstrated a significant reduction in the protein's ability to form stable triple helices.",
    "Live-cell imaging of retrograde axonal transport in neurons with the P1213L dynein heavy chain 1 variant showed a 75% decrease in the speed of cargo movement toward the cell body.",
    "Immunofluorescence of liver tissue from a patient with the R782W α₁-antitrypsin variant revealed abundant inclusions of the protein within hepatocytes, confirming its failure to be secreted.",
    "The R136Q UCHL1 variant showed a 5-fold decrease in its isopeptidase activity against a ubiquitinated substrate in a mass spectrometry-based enzymatic assay.",
    "In a fluorometric enzyme assay, the P270S glucocerebrosidase variant exhibited only 40% of the catalytic activity observed with the wild-type protein.",
    "Transmission electron microscopy of neuronal cultures expressing the A30P α-synuclein variant showed the presence of abundant fibrillar aggregates, similar to those found in Lewy bodies.",
    "In our binding assays, the R46L PCSK9 variant demonstrated a 3-fold decrease in its binding affinity for the LDL receptor, leading to a reduced rate of receptor degradation.",
    "Confocal microscopy of cells expressing the A152T tau variant revealed a significant increase in the formation of puncta and filamentous structures, suggesting enhanced aggregation."
]

non_coding_variant_sentences = [
    "Using a dual-luciferase reporter assay, we demonstrated that the SNP rs6983267, located in a long-range enhancer for the MYC oncogene, significantly increased reporter gene expression by 2.5-fold in colon cancer cell lines.",
    "Chromatin immunoprecipitation followed by sequencing (ChIP-seq) for the transcription factor TCF7L2 revealed a loss of binding at the promoter of the TCF7L2 gene in the presence of the rs7903146 risk allele.",
    "Our massively parallel reporter assay (MPRA) data showed that the A>T variant in the 3' UTR of the NOS1AP gene reduced the expression of a linked fluorescent reporter by 40% in cardiomyocyte cells.",
    "Sanger sequencing of the TERT promoter in melanoma samples identified two recurrent non-coding variants, c.-124C>T and c.-146C>T, which were shown by RT-qPCR to increase TERT mRNA expression by 15- and 20-fold, respectively.",
    "A quantitative chromatin conformation capture (3C) assay demonstrated that the rs9349379 SNP in a genomic insulator element disrupts the physical loop connecting the ESR1 promoter to its upstream enhancer.",
    "Minigene splicing assays confirmed that the deep intronic variant IVS21-12C>T in the CFTR gene leads to the creation of a cryptic splice site, resulting in a mis-spliced transcript lacking exon 22.",
    "In a yeast-based screen, we found that a 15-bp deletion within the HBB promoter region completely abolished the binding of the GATA-1 transcription factor, consistent with the observed phenotype in beta-thalassemia patients.",
    "We performed allelic expression analysis on post-mortem brain tissue and found that the rs12913832 SNP in the OCA2 gene enhancer was strongly associated with a 50% decrease in its expression.",
    "Our electro mobility shift assay (EMSA) results showed that the C>G SNP in the MDM2 promoter creates a novel high-affinity binding site for the SP1 transcription factor, leading to increased MDM2 transcription.",
    "RNA-seq analysis of patient-derived lymphoblastoid cell lines with the rs2201397 SNP in the TRIM59 3' UTR showed a significant upregulation of TRIM59 transcript levels, which we hypothesize is due to altered microRNA binding.",
    "Using CRISPR-Cas9 to introduce the rs7552554 variant in the promoter region of the MYB oncogene, we observed a 3-fold increase in H3K27ac histone marks, indicating enhanced enhancer activity.",
    "The 5-kb deletion upstream of the SOX2 gene was found to completely abrogate the expression of the gene in embryonic stem cells, suggesting the removal of a critical long-range enhancer.",
    "In a high-throughput screen, we identified an A>G variant in the promoter of a lncRNA that significantly decreased its transcription by 75% in a disease-relevant cell model.",
    "Our Northern blot analysis revealed that the rs10825036 SNP in the 3' UTR of the MIR-499 gene resulted in a mature miRNA transcript that was 50% less abundant compared to the wild-type allele.",
    "Allele-specific chromatin accessibility assays (ATAC-seq) revealed a loss of an open chromatin region at the locus containing the rs12740374 variant, suggesting a disruption of a transcription factor binding site.",
    "The 3' UTR of the KRAS gene containing the rs61764370 variant was cloned into a reporter plasmid, and subsequent luciferase assays showed a significant reduction in luciferase activity, consistent with altered miRNA-mediated repression.",
    "Chr-RNA FISH experiments confirmed that the C>T mutation in the SHH limb enhancer region failed to form a chromatin loop with the SHH promoter, explaining the observed limb malformations.",
    "Reporter gene assays showed that the rs11603334 SNP in the ARAP1 promoter led to a 2-fold upregulation of gene expression in pancreatic beta cells, which was corroborated by decreased binding of PAX4 and PAX6 transcription factors in EMSA.",
    "We used CRISPR-based tiling scans to systematically test variants in the LDLR promoter, finding that a specific A>C substitution reduced promoter activity by 60%, a key finding for familial hypercholesterolemia.",
    "RNA-seq of patient tumor samples with the rs73183594 variant in the IRF4 enhancer showed a significant increase in IRF4 mRNA expression levels, suggesting a gain-of-function mechanism.",
    "Our allele-specific sequencing analysis of RNA from heterozygous individuals demonstrated that the rs3796548 SNP, a non-coding variant, leads to a 3-fold increase in the expression of the TULP3 gene.",
    "The deletion of an enhancer 150 kb upstream of the GATA6 gene was found to cause a loss of GATA6 protein expression in pancreatic progenitor cells, as confirmed by immunostaining.",
    "Using a high-resolution 4C-seq, we mapped the chromosomal interactions of the genomic region containing a non-coding variant, revealing the creation of a novel chromatin loop between a distant enhancer and an oncogene.",
    "A minigene assay showed that a single nucleotide variant (G>A) in the 5' untranslated region of an unknown gene caused an increase in ribosome readthrough and protein translation.",
    "Quantitative real-time PCR (qRT-PCR) from patient fibroblasts with a deep intronic variant in the IDUA gene revealed a reduced level of the fully spliced transcript and an increase in a mis-spliced isoform.",
    "The C>G variant in the promoter of the CASP8 gene, located in a CpG island, was shown by methylation-specific PCR to be associated with a complete loss of DNA methylation and subsequent gene silencing.",
    "In our chromatin accessibility assay, the A>G SNP in the FTO enhancer was found to disrupt the binding of the ARID5B transcription factor, leading to a downstream effect on gene regulation.",
    "Our reporter assay demonstrated that the rs1403565 variant in the PITX2 enhancer increased the transcriptional activity of a reporter construct by 30% in cardiac tissue cells.",
    "The insertion of a SINE retrotransposon into the promoter of the FGFR2 gene was shown by reporter assays to completely abolish the gene's promoter activity in fibroblasts.",
    "CRISPR activation experiments using a sgRNA targeting the promoter region of a lncRNA confirmed that a non-coding variant within this region was responsible for a significant reduction in gene expression."
]

In [ ]:
gemini_egs = run_model(input_text=protein_variant_sentences)
filter_res(gemini_egs, "mutant")

- - - - - - Original text - - - - -
['Studies on the protein-protein interaction network revealed that the R175H '
 'variant of p53 dramatically alters its binding partners, shifting its '
 'function from a tumor suppressor to an oncogenic driver.']
- - Terms tagged of type 'mutant' - -
['r1', '75', 'h']
- - - - - - Original text - - - - -
['The structural consequences of the E6V substitution in hemoglobin are '
 'profound, leading to the formation of rigid polymers that deform red blood '
 'cells into their characteristic sickle shape.']
- - Terms tagged of type 'mutant' - -
['e6', 'v']
- - - - - - Original text - - - - -
['The D90A mutation in superoxide dismutase 1 (SOD1) highlights the complexity '
 'of disease mechanisms, as its pathogenicity in familial ALS is not due to a '
 'loss of catalytic activity but rather to a gain of toxic function.']
- - Terms tagged of type 'mutant' - -
['d', '90', 'a']
- - - - - - Original text - - - - -
['The ΔF508 deletion in the CFTR protein prevents its proper folding, '
 "triggering the cell's quality control system to target the misfolded protein "
 'for destruction in the endoplasmic reticulum.']
- - Terms tagged of type 'mutant' - -
['δf', '508']
- - - - - - Original text - - - - -
['Kinase inhibitors are now a standard therapy for melanoma patients with the '
 'V600E mutation in BRAF, which constitutively activates the downstream '
 'signaling cascade.']
- - Terms tagged of type 'mutant' - -
['v600e']
- - - - - - Original text - - - - -
['The single amino acid change A67T in transthyretin increases its propensity '
 'to misfold and aggregate, forming amyloid fibrils that deposit in the heart '
 'and other tissues.']
- - Terms tagged of type 'mutant' - -
['a6', '7', 't']
- - - - - - Original text - - - - -
['The pathogenicity of the A223P variant in fibrillin-1 lies in its disruption '
 'of calcium-binding sites, which are critical for the formation of stable '
 'microfibrils in the extracellular matrix.']
- - Terms tagged of type 'mutant' - -
['a2', '23', 'p']
- - - - - - Original text - - - - -
['Patients with familial chylomicronemia resulting from the S267L variant of '
 'lipoprotein lipase exhibit severely impaired lipid clearance due to the '
 "protein's reduced catalytic efficiency."]
- - Terms tagged of type 'mutant' - -
['s2', '67', 'l']
- - - - - - Original text - - - - -
['The R117H amino acid substitution in Factor V makes it resistant to cleavage '
 'by activated protein C, a critical step in down-regulating blood '
 'coagulation.']
- - Terms tagged of type 'mutant' - -
['r1', '17', 'h']
- - - - - - Original text - - - - -
['The P101S amino acid change in the prion protein (PrP) is a crucial '
 'determinant of disease pathology, as it favors the conversion of the normal '
 'PrP ($PrP^C$) into the disease-associated scrapie form ($PrP^{Sc}$).']
- - Terms tagged of type 'mutant' - -
['p10', '1s']
- - - - - - Original text - - - - -
['The E280A mutation in presenilin 1 alters the cleavage of the amyloid '
 'precursor protein (APP), leading to an overproduction of the highly '
 'aggregation-prone Aβ42 peptide.']
- - Terms tagged of type 'mutant' - -
['e2', '80', 'a']
- - - - - - Original text - - - - -
['Achondroplasia is caused by a G380R variant in fibroblast growth factor '
 'receptor 3 (FGFR3), which leads to the constitutive activation of the '
 'receptor even in the absence of its ligand.']
- - Terms tagged of type 'mutant' - -
['g3', '80', 'r']
- - - - - - Original text - - - - -
['The K456N variant of cardiac troponin I impairs the calcium-dependent '
 'regulation of myocardial contraction, which is the underlying cause of '
 'hypertrophic cardiomyopathy.']
- - Terms tagged of type 'mutant' - -
['k4', '56', 'n']
- - - - - - Original text - - - - -
['The C278F substitution in fibroblast growth factor receptor 2 (FGFR2) is a '
 'well-known example of a gain-of-function mutation, leading to premature '
 'fusion of the cranial sutures.']
- - Terms tagged of type 'mutant' - -
['c2', '78', 'f']
- - - - - - Original text - - - - -
['The C282Y variant in the HFE protein disrupts its interaction with the '
 'transferrin receptor, leading to a breakdown in the regulation of iron '
 'absorption.']
- - Terms tagged of type 'mutant' - -
['c2', '82', 'y']
- - - - - - Original text - - - - -
['The p.L320P variant of lamin A/C causes dilated cardiomyopathy by '
 'compromising the structural integrity of the nuclear lamina and disrupting '
 'normal gene expression patterns.']
- - Terms tagged of type 'mutant' - -
['p .', 'l3', '20', 'p']
- - - - - - Original text - - - - -
['The S295C mutation in myotilin creates a new cysteine residue, which can '
 'form inappropriate disulfide bonds, leading to the formation of aggregates '
 'that interfere with muscle function.']
- - Terms tagged of type 'mutant' - -
['s2', '95', 'c']
- - - - - - Original text - - - - -
['The R402Q variant in the ATP-binding cassette transporter A4 (ABCA4) '
 'disrupts its ability to transport retinoids, leading to the accumulation of '
 'toxic compounds in the retinal pigment epithelium.']
- - Terms tagged of type 'mutant' - -
['r4', '02', 'q']
- - - - - - Original text - - - - -
['A study of familial ALS patients identified the H46R mutation in SOD1, which '
 'was shown to lead to a misfolding and aggregation of the protein that is '
 'toxic to motor neurons.']
- - Terms tagged of type 'mutant' - -
['h4', '6', 'r']
- - - - - - Original text - - - - -
['The E258K mutation in lysosomal acid lipase is a clear example of a '
 "loss-of-function variant, as it severely impairs the protein's ability to "
 'hydrolyze cholesterol esters.']
- - Terms tagged of type 'mutant' - -
['e2', '58', 'k']
- - - - - - Original text - - - - -
['Individuals homozygous for the M34T variant in connexin 26 (GJB2) often '
 'present with non-syndromic hearing loss due to the disruption of gap '
 'junction function in the inner ear.']
- - Terms tagged of type 'mutant' - -
['m3', '4', 't']
- - - - - - Original text - - - - -
['Congenital contractural arachnodactyly is associated with the K197R mutation '
 'in fibrillin-2, a protein crucial for elastic fiber formation in connective '
 'tissues.']
- - Terms tagged of type 'mutant' - -
['k1', '97', 'r']
- - - - - - Original text - - - - -
['The L268P mutation in type II collagen (COL2A1) results in a protein with '
 'impaired triple helix formation, leading to the skeletal abnormalities '
 'characteristic of Stickler syndrome.']
- - Terms tagged of type 'mutant' - -
['l2', '68', 'p']
- - - - - - Original text - - - - -
['The P1213L variant in dynein heavy chain 1 (DYNC1H1) compromises the '
 "protein's motor function, resulting in defects in retrograde axonal "
 'transport that cause spinal muscular atrophy.']
- - Terms tagged of type 'mutant' - -
['p12', '13', 'l']
- - - - - - Original text - - - - -
['The R782W mutation in α₁-antitrypsin (SERPINA1) results in a misfolded '
 'protein that is trapped in the liver, leading to a lack of circulating '
 'α₁-antitrypsin in the lungs.']
- - Terms tagged of type 'mutant' - -
['r7', '82', 'w']
- - - - - - Original text - - - - -
['The R136Q amino acid substitution in ubiquitin carboxyl-terminal hydrolase '
 'L1 (UCHL1) affects its deubiquitinating activity, which may contribute to '
 "the accumulation of protein aggregates observed in Parkinson's disease."]
- - Terms tagged of type 'mutant' - -
['r1', '36', 'q']
- - - - - - Original text - - - - -
['The P270S variant in glucocerebrosidase (GBA1) has been shown to reduce the '
 "enzyme's activity, which is a known risk factor for Parkinson's disease."]
- - Terms tagged of type 'mutant' - -
['p27', '0', 's']
- - - - - - Original text - - - - -
['The A30P mutation in α-synuclein is a rare but well-documented cause of '
 "familial Parkinson's disease, as it promotes the formation of neurotoxic "
 'fibrils and Lewy bodies.']
- - Terms tagged of type 'mutant' - -
['a3', '0', 'p']
- - - - - - Original text - - - - -
['The R46L variant in proprotein convertase subtilisin/kexin type 9 (PCSK9) is '
 "a functional polymorphism that reduces the protein's ability to degrade LDL "
 'receptors, leading to lower levels of circulating LDL cholesterol.']
- - Terms tagged of type 'mutant' - -
['r4', '6', 'l']
- - - - - - Original text - - - - -
['The A152T variant in the protein tau (MAPT) is a known risk factor for '
 'frontotemporal dementia, as it enhances the aggregation and misfolding of '
 'the protein.']
- - Terms tagged of type 'mutant' - -
['a1', '52', 't']

In [ ]:
gemini_exps = run_model(input_text=protein_variant_sentences_experimental_results)
filter_res(gemini_exps, "mutant")

- - - - - - Original text - - - - -
['Circular dichroism spectroscopy of the R175H p53 variant revealed a '
 'significant decrease in α-helical content compared to the wild-type protein, '
 'indicating a loss of structural integrity.']
- - Terms tagged of type 'mutant' - -
['r1', '75', 'h']
- - - - - - Original text - - - - -
['In our gel electrophoresis assays, the E6V hemoglobin variant showed a '
 'distinct band shift in non-denaturing conditions, consistent with polymer '
 'formation under deoxygenated states.']
- - Terms tagged of type 'mutant' - -
['e6', 'v']
- - - - - - Original text - - - - -
['Immunoblot analysis of cells expressing the D90A SOD1 variant demonstrated a '
 'marked increase in detergent-insoluble protein, suggesting a propensity for '
 'aggregation.']
- - Terms tagged of type 'mutant' - -
['d', '90', 'a']
- - - - - - Original text - - - - -
['Western blot analysis of the ΔF508 CFTR variant showed a complete absence of '
 'the mature, fully glycosylated band, confirming that the protein is not '
 'trafficked to the cell surface.']
- - Terms tagged of type 'mutant' - -
['δf', '508']
- - - - - - Original text - - - - -
['In vitro kinase assays confirmed a 500-fold increase in the phosphorylation '
 'of ERK and MEK substrates when using the V600E BRAF variant, demonstrating '
 'constitutive activation.']
- - Terms tagged of type 'mutant' - -
['v600e']
- - - - - - Original text - - - - -
['Fluorescence microscopy with Thioflavin S staining revealed abundant amyloid '
 'deposits in cardiac tissue sections from mice expressing the A67T '
 'transthyretin variant.']
- - Terms tagged of type 'mutant' - -
['a6', '7', 't']
- - - - - - Original text - - - - -
['Our surface plasmon resonance (SPR) data demonstrated that the A223P '
 'fibrillin-1 variant has a significantly reduced binding affinity for calcium '
 'ions (Kd = 450 nM vs 50 nM for WT).']
- - Terms tagged of type 'mutant' - -
['a2', '23', 'p']
- - - - - - Original text - - - - -
['Lipolysis assays using the S267L lipoprotein lipase variant showed only 15% '
 'of the catalytic activity observed with the wild-type enzyme.']
- - Terms tagged of type 'mutant' - -
['s2', '67', 'l']
- - - - - - Original text - - - - -
['Coagulation assays of plasma containing the R117H Factor V variant showed a '
 '12-fold increase in clotting time after the addition of activated protein C, '
 'confirming its resistance to inactivation.']
- - Terms tagged of type 'mutant' - -
['r1', '17', 'h']
- - - - - - Original text - - - - -
['Real-time quaking-induced conversion (RT-QuIC) assays demonstrated that the '
 'P101S prion protein variant seeded the rapid formation of fibrils at a '
 'concentration 100-fold lower than the wild-type protein.']
- - Terms tagged of type 'mutant' - -
['p10', '1s']
- - - - - - Original text - - - - -
['Cell-free cleavage assays confirmed that the E280A presenilin 1 variant '
 'preferentially generated the highly amyloidogenic Aβ42 peptide over the Aβ40 '
 'peptide.']
- - Terms tagged of type 'mutant' - -
['e2', '80', 'a']
- - - - - - Original text - - - - -
['Dual-luciferase reporter assays confirmed a 20-fold increase in STAT3 '
 'signaling in cells expressing the G380R FGFR3 variant, even in the absence '
 'of exogenous FGF ligand.']
- - Terms tagged of type 'mutant' - -
['g3', '80', 'r']
- - - - - - Original text - - - - -
['Calcium-sensitizing assays on skinned cardiac muscle fibers revealed that '
 'the K456N troponin I variant increased the calcium sensitivity of force '
 'generation by 2.5-fold.']
- - Terms tagged of type 'mutant' - -
['k4', '56', 'n']
- - - - - - Original text - - - - -
['Immunofluorescence staining revealed that the C278F FGFR2 variant localized '
 'to the cell membrane at a higher density and for a longer duration than the '
 'wild-type protein.']
- - Terms tagged of type 'mutant' - -
['c2', '78', 'f']
- - - - - - Original text - - - - -
['In our iron uptake experiments, cells expressing the C282Y HFE variant '
 'failed to show the characteristic down-regulation of transferrin receptor '
 'expression in response to high iron levels.']
- - Terms tagged of type 'mutant' - -
['c2', '82', 'y']
- - - - - - Original text - - - - -
['Immunoblotting of nuclear fractions showed a fragmented lamin A/C network in '
 'cells from patients with the p.L320P variant, indicating a loss of nuclear '
 'integrity.']
- - Terms tagged of type 'mutant' - -
['p .', 'l3', '20', 'p']
- - - - - - Original text - - - - -
['Pull-down assays with a cysteine-reactive probe demonstrated that the S295C '
 'myotilin mutation forms intermolecular disulfide bonds, leading to the '
 'formation of high-molecular-weight aggregates.']
- - Terms tagged of type 'mutant' - -
['s2', '95', 'c']
- - - - - - Original text - - - - -
['Liposome-based transport assays using the R402Q ABCA4 variant showed a 90% '
 'reduction in the translocation of all-trans-retinal across the membrane.']
- - Terms tagged of type 'mutant' - -
['r4', '02', 'q']
- - - - - - Original text - - - - -
['Immunohistochemistry of spinal cord sections from transgenic mice expressing '
 'the H46R SOD1 variant revealed extensive intracellular inclusions in motor '
 'neurons, which were immunoreactive for ubiquitin.']
- - Terms tagged of type 'mutant' - -
['h4', '6', 'r']
- - - - - - Original text - - - - -
['In vitro enzyme kinetics demonstrated that the E258K lysosomal acid lipase '
 'variant had a Vmax that was less than 5% of the wild-type enzyme, confirming '
 'a severe loss-of-function.']
- - Terms tagged of type 'mutant' - -
['e2', '58', 'k']
- - - - - - Original text - - - - -
['Dye-transfer assays showed a complete failure of Lucifer yellow transfer '
 'between cells expressing the M34T connexin 26 variant, indicating a loss of '
 'gap junction function.']
- - Terms tagged of type 'mutant' - -
['m3', '4', 't']
- - - - - - Original text - - - - -
['Atomic force microscopy of extracellular matrix fibers from cells expressing '
 'the K197R fibrillin-2 variant revealed an aberrant, disorganized microfibril '
 'network.']
- - Terms tagged of type 'mutant' - -
['k1', '97', 'r']
- - - - - - Original text - - - - -
['A triple helix formation assay using purified L268P collagen type II '
 "demonstrated a significant reduction in the protein's ability to form stable "
 'triple helices.']
- - Terms tagged of type 'mutant' - -
['l2', '68', 'p']
- - - - - - Original text - - - - -
['Live-cell imaging of retrograde axonal transport in neurons with the P1213L '
 'dynein heavy chain 1 variant showed a 75% decrease in the speed of cargo '
 'movement toward the cell body.']
- - Terms tagged of type 'mutant' - -
['p12', '13', 'l']
- - - - - - Original text - - - - -
['Immunofluorescence of liver tissue from a patient with the R782W '
 'α₁-antitrypsin variant revealed abundant inclusions of the protein within '
 'hepatocytes, confirming its failure to be secreted.']
- - Terms tagged of type 'mutant' - -
['r7', '82', 'w']
- - - - - - Original text - - - - -
['The R136Q UCHL1 variant showed a 5-fold decrease in its isopeptidase '
 'activity against a ubiquitinated substrate in a mass spectrometry-based '
 'enzymatic assay.']
- - Terms tagged of type 'mutant' - -
['r1', '36', 'q']
- - - - - - Original text - - - - -
['In a fluorometric enzyme assay, the P270S glucocerebrosidase variant '
 'exhibited only 40% of the catalytic activity observed with the wild-type '
 'protein.']
- - Terms tagged of type 'mutant' - -
['p27', '0', 's']
- - - - - - Original text - - - - -
['Transmission electron microscopy of neuronal cultures expressing the A30P '
 'α-synuclein variant showed the presence of abundant fibrillar aggregates, '
 'similar to those found in Lewy bodies.']
- - Terms tagged of type 'mutant' - -
['a3', '0', 'p']
- - - - - - Original text - - - - -
['In our binding assays, the R46L PCSK9 variant demonstrated a 3-fold decrease '
 'in its binding affinity for the LDL receptor, leading to a reduced rate of '
 'receptor degradation.']
- - Terms tagged of type 'mutant' - -
['r4', '6', 'l']
- - - - - - Original text - - - - -
['Confocal microscopy of cells expressing the A152T tau variant revealed a '
 'significant increase in the formation of puncta and filamentous structures, '
 'suggesting enhanced aggregation.']
- - Terms tagged of type 'mutant' - -
['a1', '52', 't']

In [ ]:
gemini_gene = run_model(input_text=non_coding_variant_sentences)
filter_res(gemini_gene, "mutant")

- - - - - - Original text - - - - -
['Our massively parallel reporter assay (MPRA) data showed that the A>T '
 "variant in the 3' UTR of the NOS1AP gene reduced the expression of a linked "
 'fluorescent reporter by 40% in cardiomyocyte cells.']
- - Terms tagged of type 'mutant' - -
['a > t']
- - - - - - Original text - - - - -
['Sanger sequencing of the TERT promoter in melanoma samples identified two '
 'recurrent non-coding variants, c.-124C>T and c.-146C>T, which were shown by '
 'RT-qPCR to increase TERT mRNA expression by 15- and 20-fold, respectively.']
- - Terms tagged of type 'mutant' - -
['c . - 124 c > t', 'c . - 146 c > t']
- - - - - - Original text - - - - -
['Minigene splicing assays confirmed that the deep intronic variant '
 'IVS21-12C>T in the CFTR gene leads to the creation of a cryptic splice site, '
 'resulting in a mis-spliced transcript lacking exon 22.']
- - Terms tagged of type 'mutant' - -
['iv', 's2', '1 - 12 c > t']
- - - - - - Original text - - - - -
['Our electro mobility shift assay (EMSA) results showed that the C>G SNP in '
 'the MDM2 promoter creates a novel high-affinity binding site for the SP1 '
 'transcription factor, leading to increased MDM2 transcription.']
- - Terms tagged of type 'mutant' - -
['c > g']
- - - - - - Original text - - - - -
['Using CRISPR-Cas9 to introduce the rs7552554 variant in the promoter region '
 'of the MYB oncogene, we observed a 3-fold increase in H3K27ac histone marks, '
 'indicating enhanced enhancer activity.']
- - Terms tagged of type 'mutant' - -
['rs7', '55', '255', '4']
- - - - - - Original text - - - - -
['Allele-specific chromatin accessibility assays (ATAC-seq) revealed a loss of '
 'an open chromatin region at the locus containing the rs12740374 variant, '
 'suggesting a disruption of a transcription factor binding site.']
- - Terms tagged of type 'mutant' - -
['rs', '127', '403', '74']
- - - - - - Original text - - - - -
["The 3' UTR of the KRAS gene containing the rs61764370 variant was cloned "
 'into a reporter plasmid, and subsequent luciferase assays showed a '
 'significant reduction in luciferase activity, consistent with altered '
 'miRNA-mediated repression.']
- - Terms tagged of type 'mutant' - -
['61', '76', '43']
- - - - - - Original text - - - - -
['Chr-RNA FISH experiments confirmed that the C>T mutation in the SHH limb '
 'enhancer region failed to form a chromatin loop with the SHH promoter, '
 'explaining the observed limb malformations.']
- - Terms tagged of type 'mutant' - -
['c > t']
- - - - - - Original text - - - - -
['We used CRISPR-based tiling scans to systematically test variants in the '
 'LDLR promoter, finding that a specific A>C substitution reduced promoter '
 'activity by 60%, a key finding for familial hypercholesterolemia.']
- - Terms tagged of type 'mutant' - -
['a > c']
- - - - - - Original text - - - - -
["A minigene assay showed that a single nucleotide variant (G>A) in the 5' "
 'untranslated region of an unknown gene caused an increase in ribosome '
 'readthrough and protein translation.']
- - Terms tagged of type 'mutant' - -
['g > a']
- - - - - - Original text - - - - -
['The C>G variant in the promoter of the CASP8 gene, located in a CpG island, '
 'was shown by methylation-specific PCR to be associated with a complete loss '
 'of DNA methylation and subsequent gene silencing.']
- - Terms tagged of type 'mutant' - -
['c > g']
- - - - - - Original text - - - - -
['In our chromatin accessibility assay, the A>G SNP in the FTO enhancer was '
 'found to disrupt the binding of the ARID5B transcription factor, leading to '
 'a downstream effect on gene regulation.']
- - Terms tagged of type 'mutant' - -
['a > g']
- - - - - - Original text - - - - -
['Our reporter assay demonstrated that the rs1403565 variant in the PITX2 '
 'enhancer increased the transcriptional activity of a reporter construct by '
 '30% in cardiac tissue cells.']
- - Terms tagged of type 'mutant' - -
['rs', '140', '35', '65']

In [ ]:
filter_res(gemini_gene, "protein")

- - - - - - Original text - - - - -
['Chromatin immunoprecipitation followed by sequencing (ChIP-seq) for the '
 'transcription factor TCF7L2 revealed a loss of binding at the promoter of '
 'the TCF7L2 gene in the presence of the rs7903146 risk allele.']
- - Terms tagged of type 'protein' - -
['tcf', '7', 'l2', 'tcf', '7', 'l2']
- - - - - - Original text - - - - -
['Our massively parallel reporter assay (MPRA) data showed that the A>T '
 "variant in the 3' UTR of the NOS1AP gene reduced the expression of a linked "
 'fluorescent reporter by 40% in cardiomyocyte cells.']
- - Terms tagged of type 'protein' - -
['nos', '1a', 'p']
- - - - - - Original text - - - - -
['Sanger sequencing of the TERT promoter in melanoma samples identified two '
 'recurrent non-coding variants, c.-124C>T and c.-146C>T, which were shown by '
 'RT-qPCR to increase TERT mRNA expression by 15- and 20-fold, respectively.']
- - Terms tagged of type 'protein' - -
['tert', 'tert']
- - - - - - Original text - - - - -
['A quantitative chromatin conformation capture (3C) assay demonstrated that '
 'the rs9349379 SNP in a genomic insulator element disrupts the physical loop '
 'connecting the ESR1 promoter to its upstream enhancer.']
- - Terms tagged of type 'protein' - -
['esr1']
- - - - - - Original text - - - - -
['Minigene splicing assays confirmed that the deep intronic variant '
 'IVS21-12C>T in the CFTR gene leads to the creation of a cryptic splice site, '
 'resulting in a mis-spliced transcript lacking exon 22.']
- - Terms tagged of type 'protein' - -
['cftr']
- - - - - - Original text - - - - -
['We performed allelic expression analysis on post-mortem brain tissue and '
 'found that the rs12913832 SNP in the OCA2 gene enhancer was strongly '
 'associated with a 50% decrease in its expression.']
- - Terms tagged of type 'protein' - -
['oc', 'a2']
- - - - - - Original text - - - - -
['Our electro mobility shift assay (EMSA) results showed that the C>G SNP in '
 'the MDM2 promoter creates a novel high-affinity binding site for the SP1 '
 'transcription factor, leading to increased MDM2 transcription.']
- - Terms tagged of type 'protein' - -
['mdm2', 'sp1', 'mdm2']
- - - - - - Original text - - - - -
['RNA-seq analysis of patient-derived lymphoblastoid cell lines with the '
 "rs2201397 SNP in the TRIM59 3' UTR showed a significant upregulation of "
 'TRIM59 transcript levels, which we hypothesize is due to altered microRNA '
 'binding.']
- - Terms tagged of type 'protein' - -
['trim', '59', 'trim', '59']
- - - - - - Original text - - - - -
['Using CRISPR-Cas9 to introduce the rs7552554 variant in the promoter region '
 'of the MYB oncogene, we observed a 3-fold increase in H3K27ac histone marks, '
 'indicating enhanced enhancer activity.']
- - Terms tagged of type 'protein' - -
['myb']
- - - - - - Original text - - - - -
['The 5-kb deletion upstream of the SOX2 gene was found to completely abrogate '
 'the expression of the gene in embryonic stem cells, suggesting the removal '
 'of a critical long-range enhancer.']
- - Terms tagged of type 'protein' - -
['sox2']
- - - - - - Original text - - - - -
["Our Northern blot analysis revealed that the rs10825036 SNP in the 3' UTR of "
 'the MIR-499 gene resulted in a mature miRNA transcript that was 50% less '
 'abundant compared to the wild-type allele.']
- - Terms tagged of type 'protein' - -
['mir - 499']
- - - - - - Original text - - - - -
["The 3' UTR of the KRAS gene containing the rs61764370 variant was cloned "
 'into a reporter plasmid, and subsequent luciferase assays showed a '
 'significant reduction in luciferase activity, consistent with altered '
 'miRNA-mediated repression.']
- - Terms tagged of type 'protein' - -
['kras']
- - - - - - Original text - - - - -
['Chr-RNA FISH experiments confirmed that the C>T mutation in the SHH limb '
 'enhancer region failed to form a chromatin loop with the SHH promoter, '
 'explaining the observed limb malformations.']
- - Terms tagged of type 'protein' - -
['shh', 'shh']
- - - - - - Original text - - - - -
['Reporter gene assays showed that the rs11603334 SNP in the ARAP1 promoter '
 'led to a 2-fold upregulation of gene expression in pancreatic beta cells, '
 'which was corroborated by decreased binding of PAX4 and PAX6 transcription '
 'factors in EMSA.']
- - Terms tagged of type 'protein' - -
['ara', 'p1', 'pax', '4', 'pax6']
- - - - - - Original text - - - - -
['We used CRISPR-based tiling scans to systematically test variants in the '
 'LDLR promoter, finding that a specific A>C substitution reduced promoter '
 'activity by 60%, a key finding for familial hypercholesterolemia.']
- - Terms tagged of type 'protein' - -
['ldlr']
- - - - - - Original text - - - - -
['RNA-seq of patient tumor samples with the rs73183594 variant in the IRF4 '
 'enhancer showed a significant increase in IRF4 mRNA expression levels, '
 'suggesting a gain-of-function mechanism.']
- - Terms tagged of type 'protein' - -
['irf', '4', 'irf', '4']
- - - - - - Original text - - - - -
['Our allele-specific sequencing analysis of RNA from heterozygous individuals '
 'demonstrated that the rs3796548 SNP, a non-coding variant, leads to a 3-fold '
 'increase in the expression of the TULP3 gene.']
- - Terms tagged of type 'protein' - -
['tul', 'p3']
- - - - - - Original text - - - - -
['The deletion of an enhancer 150 kb upstream of the GATA6 gene was found to '
 'cause a loss of GATA6 protein expression in pancreatic progenitor cells, as '
 'confirmed by immunostaining.']
- - Terms tagged of type 'protein' - -
['gata', '6', 'gata', '6']
- - - - - - Original text - - - - -
['Quantitative real-time PCR (qRT-PCR) from patient fibroblasts with a deep '
 'intronic variant in the IDUA gene revealed a reduced level of the fully '
 'spliced transcript and an increase in a mis-spliced isoform.']
- - Terms tagged of type 'protein' - -
['id', 'ua']
- - - - - - Original text - - - - -
['The C>G variant in the promoter of the CASP8 gene, located in a CpG island, '
 'was shown by methylation-specific PCR to be associated with a complete loss '
 'of DNA methylation and subsequent gene silencing.']
- - Terms tagged of type 'protein' - -
['casp', '8']
- - - - - - Original text - - - - -
['In our chromatin accessibility assay, the A>G SNP in the FTO enhancer was '
 'found to disrupt the binding of the ARID5B transcription factor, leading to '
 'a downstream effect on gene regulation.']
- - Terms tagged of type 'protein' - -
['fto', 'arid', '5b']
- - - - - - Original text - - - - -
['Our reporter assay demonstrated that the rs1403565 variant in the PITX2 '
 'enhancer increased the transcriptional activity of a reporter construct by '
 '30% in cardiac tissue cells.']
- - Terms tagged of type 'protein' - -
['pit', 'x2']
- - - - - - Original text - - - - -
['The insertion of a SINE retrotransposon into the promoter of the FGFR2 gene '
 "was shown by reporter assays to completely abolish the gene's promoter "
 'activity in fibroblasts.']
- - Terms tagged of type 'protein' - -
['fgfr2']

In [ ]:
gemini_gene

[('Using a dual-luciferase reporter assay, we demonstrated that the SNP rs6983267, located in a long-range enhancer for the MYC oncogene, significantly increased reporter gene expression by 2.5-fold in colon cancer cell lines.',
  [{'entity': 'dual - luciferase reporter assay',
    'type': 'experimental_method'},
   {'entity': 'rs', 'type': 'gene'},
   {'entity': '69', 'type': 'gene'},
   {'entity': '83', 'type': 'gene'},
   {'entity': '267', 'type': 'gene'},
   {'entity': 'long - range enhancer', 'type': 'structure_element'},
   {'entity': 'myc', 'type': 'protein_type'}]),
 ('Chromatin immunoprecipitation followed by sequencing (ChIP-seq) for the transcription factor TCF7L2 revealed a loss of binding at the promoter of the TCF7L2 gene in the presence of the rs7903146 risk allele.',
  [{'entity': 'chromatin immunoprecipitation followed by sequencing',
    'type': 'experimental_method'},
   {'entity': 'chip - seq', 'type': 'experimental_method'},
   {'entity': 'transcription factor', 'type': 'protein_type'},
   {'entity': 'tcf', 'type': 'protein'},
   {'entity': '7', 'type': 'protein'},
   {'entity': 'l2', 'type': 'protein'},
   {'entity': 'tcf', 'type': 'protein'},
   {'entity': '7', 'type': 'protein'},
   {'entity': 'l2', 'type': 'protein'}]),
 ("Our massively parallel reporter assay (MPRA) data showed that the A>T variant in the 3' UTR of the NOS1AP gene reduced the expression of a linked fluorescent reporter by 40% in cardiomyocyte cells.",
  [{'entity': 'massive', 'type': 'experimental_method'},
   {'entity': 'ly parallel reporter assay', 'type': 'experimental_method'},
   {'entity': 'mpr', 'type': 'experimental_method'},
   {'entity': 'a', 'type': 'experimental_method'},
   {'entity': 'a > t', 'type': 'mutant'},
   {'entity': "3 ' utr", 'type': 'structure_element'},
   {'entity': 'nos', 'type': 'protein'},
   {'entity': '1a', 'type': 'protein'},
   {'entity': 'p', 'type': 'protein'}]),
 ('Sanger sequencing of the TERT promoter in melanoma samples identified two recurrent non-coding variants, c.-124C>T and c.-146C>T, which were shown by RT-qPCR to increase TERT mRNA expression by 15- and 20-fold, respectively.',
  [{'entity': 'sanger sequencing', 'type': 'experimental_method'},
   {'entity': 'tert', 'type': 'protein'},
   {'entity': 'c . - 124 c > t', 'type': 'mutant'},
   {'entity': 'c . - 146 c > t', 'type': 'mutant'},
   {'entity': 'rt - qpcr', 'type': 'experimental_method'},
   {'entity': 'tert', 'type': 'protein'}]),
 ('A quantitative chromatin conformation capture (3C) assay demonstrated that the rs9349379 SNP in a genomic insulator element disrupts the physical loop connecting the ESR1 promoter to its upstream enhancer.',
  [{'entity': 'quantitative chromatin conformation capture (',
    'type': 'experimental_method'},
   {'entity': '3c', 'type': 'experimental_method'},
   {'entity': '93', 'type': 'gene'},
   {'entity': '49', 'type': 'gene'},
   {'entity': 'esr1', 'type': 'protein'},
   {'entity': 'enhancer', 'type': 'structure_element'}]),
 ('Minigene splicing assays confirmed that the deep intronic variant IVS21-12C>T in the CFTR gene leads to the creation of a cryptic splice site, resulting in a mis-spliced transcript lacking exon 22.',
  [{'entity': 'mini', 'type': 'experimental_method'},
   {'entity': 'gene splicing assays', 'type': 'experimental_method'},
   {'entity': 'iv', 'type': 'mutant'},
   {'entity': 's2', 'type': 'mutant'},
   {'entity': '1 - 12 c > t', 'type': 'mutant'},
   {'entity': 'cftr', 'type': 'protein'},
   {'entity': 'cryptic', 'type': 'site'},
   {'entity': 'splice site', 'type': 'site'},
   {'entity': 'exon 22', 'type': 'structure_element'}]),
 ('In a yeast-based screen, we found that a 15-bp deletion within the HBB promoter region completely abolished the binding of the GATA-1 transcription factor, consistent with the observed phenotype in beta-thalassemia patients.',
  [{'entity': 'yeast - based screen', 'type': 'experimental_method'},
   {'entity': '15', 'type': 'residue_range'},
   {'entity': 'deletion', 'type': 'experimental_method'},
   {'entity': 'hb', 'type': 'gene'},
   {'entity': 'b', 'type': 'gene'},
   {'entity': 'gata - 1 transcription factor', 'type': 'protein_type'}]),
 ('We performed allelic expression analysis on post-mortem brain tissue and found that the rs12913832 SNP in the OCA2 gene enhancer was strongly associated with a 50% decrease in its expression.',
  [{'entity': 'allelic expression analysis', 'type': 'experimental_method'},
   {'entity': 'rs', 'type': 'gene'},
   {'entity': '129', 'type': 'gene'},
   {'entity': '138', 'type': 'gene'},
   {'entity': '32', 'type': 'gene'},
   {'entity': 'oc', 'type': 'protein'},
   {'entity': 'a2', 'type': 'protein'}]),
 ('Our electro mobility shift assay (EMSA) results showed that the C>G SNP in the MDM2 promoter creates a novel high-affinity binding site for the SP1 transcription factor, leading to increased MDM2 transcription.',
  [{'entity': 'electro mobility shift assay', 'type': 'experimental_method'},
   {'entity': 'emsa', 'type': 'experimental_method'},
   {'entity': 'c > g', 'type': 'mutant'},
   {'entity': 'mdm2', 'type': 'protein'},
   {'entity': 'high - affinity binding site', 'type': 'site'},
   {'entity': 'sp1', 'type': 'protein'},
   {'entity': 'mdm2', 'type': 'protein'}]),
 ("RNA-seq analysis of patient-derived lymphoblastoid cell lines with the rs2201397 SNP in the TRIM59 3' UTR showed a significant upregulation of TRIM59 transcript levels, which we hypothesize is due to altered microRNA binding.",
  [{'entity': 'rna - seq', 'type': 'experimental_method'},
   {'entity': '22', 'type': 'gene'},
   {'entity': '01', 'type': 'gene'},
   {'entity': '397', 'type': 'gene'},
   {'entity': 'trim', 'type': 'protein'},
   {'entity': '59', 'type': 'protein'},
   {'entity': "3 ' utr", 'type': 'structure_element'},
   {'entity': 'trim', 'type': 'protein'},
   {'entity': '59', 'type': 'protein'},
   {'entity': 'microrna', 'type': 'chemical'}]),
 ('Using CRISPR-Cas9 to introduce the rs7552554 variant in the promoter region of the MYB oncogene, we observed a 3-fold increase in H3K27ac histone marks, indicating enhanced enhancer activity.',
  [{'entity': 'crispr - cas9', 'type': 'experimental_method'},
   {'entity': 'rs7', 'type': 'mutant'},
   {'entity': '55', 'type': 'mutant'},
   {'entity': '255', 'type': 'mutant'},
   {'entity': '4', 'type': 'mutant'},
   {'entity': 'myb', 'type': 'protein'}]),
 ('The 5-kb deletion upstream of the SOX2 gene was found to completely abrogate the expression of the gene in embryonic stem cells, suggesting the removal of a critical long-range enhancer.',
  [{'entity': 'deletion', 'type': 'experimental_method'},
   {'entity': 'sox2', 'type': 'protein'}]),
 ('In a high-throughput screen, we identified an A>G variant in the promoter of a lncRNA that significantly decreased its transcription by 75% in a disease-relevant cell model.',
  [{'entity': 'high - throughput screen', 'type': 'experimental_method'},
   {'entity': 'a > g', 'type': 'residue_name'},
   {'entity': 'lncrna', 'type': 'protein_type'}]),
 ("Our Northern blot analysis revealed that the rs10825036 SNP in the 3' UTR of the MIR-499 gene resulted in a mature miRNA transcript that was 50% less abundant compared to the wild-type allele.",
  [{'entity': 'northern blot analysis', 'type': 'experimental_method'},
   {'entity': 'rs10', 'type': 'gene'},
   {'entity': '82', 'type': 'gene'},
   {'entity': '50', 'type': 'gene'},
   {'entity': '36', 'type': 'gene'},
   {'entity': "3 ' utr", 'type': 'structure_element'},
   {'entity': 'mir - 499', 'type': 'protein'},
   {'entity': 'mirna', 'type': 'chemical'},
   {'entity': 'wild - type', 'type': 'protein_state'}]),
 ('Allele-specific chromatin accessibility assays (ATAC-seq) revealed a loss of an open chromatin region at the locus containing the rs12740374 variant, suggesting a disruption of a transcription factor binding site.',
  [{'entity': 'allele - specific chromatin accessibility assays',
    'type': 'experimental_method'},
   {'entity': 'ata', 'type': 'experimental_method'},
   {'entity': 'c - seq', 'type': 'experimental_method'},
   {'entity': 'rs', 'type': 'mutant'},
   {'entity': '127', 'type': 'mutant'},
   {'entity': '403', 'type': 'mutant'},
   {'entity': '74', 'type': 'mutant'},
   {'entity': 'transcription factor binding site', 'type': 'site'}]),
 ("The 3' UTR of the KRAS gene containing the rs61764370 variant was cloned into a reporter plasmid, and subsequent luciferase assays showed a significant reduction in luciferase activity, consistent with altered miRNA-mediated repression.",
  [{'entity': "3 ' utr", 'type': 'structure_element'},
   {'entity': 'kras', 'type': 'protein'},
   {'entity': '61', 'type': 'mutant'},
   {'entity': '76', 'type': 'mutant'},
   {'entity': '43', 'type': 'mutant'},
   {'entity': 'luciferase assays', 'type': 'experimental_method'},
   {'entity': 'mirna', 'type': 'chemical'}]),
 ('Chr-RNA FISH experiments confirmed that the C>T mutation in the SHH limb enhancer region failed to form a chromatin loop with the SHH promoter, explaining the observed limb malformations.',
  [{'entity': 'chr - rna fish', 'type': 'experimental_method'},
   {'entity': 'c > t', 'type': 'mutant'},
   {'entity': 'shh', 'type': 'protein'},
   {'entity': 'shh', 'type': 'protein'}]),
 ('Reporter gene assays showed that the rs11603334 SNP in the ARAP1 promoter led to a 2-fold upregulation of gene expression in pancreatic beta cells, which was corroborated by decreased binding of PAX4 and PAX6 transcription factors in EMSA.',
  [{'entity': 'reporter gene assays', 'type': 'experimental_method'},
   {'entity': 'rs', 'type': 'gene'},
   {'entity': '116', 'type': 'gene'},
   {'entity': '03', 'type': 'gene'},
   {'entity': '33', 'type': 'gene'},
   {'entity': '4', 'type': 'gene'},
   {'entity': 'ara', 'type': 'protein'},
   {'entity': 'p1', 'type': 'protein'},
   {'entity': 'pax', 'type': 'protein'},
   {'entity': '4', 'type': 'protein'},
   {'entity': 'pax6', 'type': 'protein'},
   {'entity': 'emsa', 'type': 'experimental_method'}]),
 ('We used CRISPR-based tiling scans to systematically test variants in the LDLR promoter, finding that a specific A>C substitution reduced promoter activity by 60%, a key finding for familial hypercholesterolemia.',
  [{'entity': 'crispr - based til ing scans', 'type': 'experimental_method'},
   {'entity': 'ldlr', 'type': 'protein'},
   {'entity': 'a > c', 'type': 'mutant'}]),
 ('RNA-seq of patient tumor samples with the rs73183594 variant in the IRF4 enhancer showed a significant increase in IRF4 mRNA expression levels, suggesting a gain-of-function mechanism.',
  [{'entity': 'rna - seq', 'type': 'experimental_method'},
   {'entity': 'irf', 'type': 'protein'},
   {'entity': '4', 'type': 'protein'},
   {'entity': 'irf', 'type': 'protein'},
   {'entity': '4', 'type': 'protein'}]),
 ('Our allele-specific sequencing analysis of RNA from heterozygous individuals demonstrated that the rs3796548 SNP, a non-coding variant, leads to a 3-fold increase in the expression of the TULP3 gene.',
  [{'entity': 'allele - specific sequencing analysis',
    'type': 'experimental_method'},
   {'entity': 'rna', 'type': 'chemical'},
   {'entity': 'rs', 'type': 'gene'},
   {'entity': '37', 'type': 'gene'},
   {'entity': '96', 'type': 'gene'},
   {'entity': '54', 'type': 'gene'},
   {'entity': '8', 'type': 'gene'},
   {'entity': 'tul', 'type': 'protein'},
   {'entity': 'p3', 'type': 'protein'}]),
 ('The deletion of an enhancer 150 kb upstream of the GATA6 gene was found to cause a loss of GATA6 protein expression in pancreatic progenitor cells, as confirmed by immunostaining.',
  [{'entity': 'deletion of', 'type': 'experimental_method'},
   {'entity': 'enhancer', 'type': 'structure_element'},
   {'entity': 'gata', 'type': 'protein'},
   {'entity': '6', 'type': 'protein'},
   {'entity': 'gata', 'type': 'protein'},
   {'entity': '6', 'type': 'protein'},
   {'entity': 'immunostaining', 'type': 'experimental_method'}]),
 ('Using a high-resolution 4C-seq, we mapped the chromosomal interactions of the genomic region containing a non-coding variant, revealing the creation of a novel chromatin loop between a distant enhancer and an oncogene.',
  [{'entity': '4c - seq', 'type': 'experimental_method'}]),
 ("A minigene assay showed that a single nucleotide variant (G>A) in the 5' untranslated region of an unknown gene caused an increase in ribosome readthrough and protein translation.",
  [{'entity': 'mini', 'type': 'experimental_method'},
   {'entity': 'gene assay', 'type': 'experimental_method'},
   {'entity': 'g > a', 'type': 'mutant'},
   {'entity': "5 ' untranslated region", 'type': 'structure_element'}]),
 ('Quantitative real-time PCR (qRT-PCR) from patient fibroblasts with a deep intronic variant in the IDUA gene revealed a reduced level of the fully spliced transcript and an increase in a mis-spliced isoform.',
  [{'entity': 'quantitative real - time pcr', 'type': 'experimental_method'},
   {'entity': 'qrt - pcr', 'type': 'experimental_method'},
   {'entity': 'id', 'type': 'protein'},
   {'entity': 'ua', 'type': 'protein'},
   {'entity': 'fully spliced', 'type': 'protein_state'}]),
 ('The C>G variant in the promoter of the CASP8 gene, located in a CpG island, was shown by methylation-specific PCR to be associated with a complete loss of DNA methylation and subsequent gene silencing.',
  [{'entity': 'c > g', 'type': 'mutant'},
   {'entity': 'casp', 'type': 'protein'},
   {'entity': '8', 'type': 'protein'},
   {'entity': 'cpg island', 'type': 'site'},
   {'entity': 'methylation - specific pcr', 'type': 'experimental_method'}]),
 ('In our chromatin accessibility assay, the A>G SNP in the FTO enhancer was found to disrupt the binding of the ARID5B transcription factor, leading to a downstream effect on gene regulation.',
  [{'entity': 'chromatin accessibility assay', 'type': 'experimental_method'},
   {'entity': 'a > g', 'type': 'mutant'},
   {'entity': 'fto', 'type': 'protein'},
   {'entity': 'arid', 'type': 'protein'},
   {'entity': '5b', 'type': 'protein'}]),
 ('Our reporter assay demonstrated that the rs1403565 variant in the PITX2 enhancer increased the transcriptional activity of a reporter construct by 30% in cardiac tissue cells.',
  [{'entity': 'reporter assay', 'type': 'experimental_method'},
   {'entity': 'rs', 'type': 'mutant'},
   {'entity': '140', 'type': 'mutant'},
   {'entity': '35', 'type': 'mutant'},
   {'entity': '65', 'type': 'mutant'},
   {'entity': 'pit', 'type': 'protein'},
   {'entity': 'x2', 'type': 'protein'}]),
 ("The insertion of a SINE retrotransposon into the promoter of the FGFR2 gene was shown by reporter assays to completely abolish the gene's promoter activity in fibroblasts.",
  [{'entity': 'sine retrotranspos on', 'type': 'protein_type'},
   {'entity': 'fgfr2', 'type': 'protein'},
   {'entity': 'reporter assays', 'type': 'experimental_method'}]),
 ('CRISPR activation experiments using a sgRNA targeting the promoter region of a lncRNA confirmed that a non-coding variant within this region was responsible for a significant reduction in gene expression.',
  [{'entity': 'crispr activation experiments', 'type': 'experimental_method'},
   {'entity': 'sgrna', 'type': 'chemical'},
   {'entity': 'lncrna', 'type': 'protein_type'}])]

### AE classifier - not worth chasing

In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# This model is a classifier: AE is / is not present in text
tokenizer = AutoTokenizer.from_pretrained("jocforero/longformer-adverse-event-classifier")
ae_model = AutoModelForSequenceClassification.from_pretrained("jocforero/longformer-adverse-event-classifier")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/961 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/595M [00:00<?, ?B/s]

In [17]:
gemini_ae_egs = [
    "Gastrointestinal bleeding occurred in two patients receiving the active treatment."
    "One participant in the control group experienced anaphylactic shock requiring immediate medical intervention.",
    "The most frequently reported adverse event was mild-to-moderate headache, observed in 15% of the study population.",
    "Three cases of acute renal failure were documented, leading to discontinuation of the study drug.",
    "A dose-dependent increase in serum transaminases was observed in a subset of participants.",
    "The device's implantation was associated with local tissue necrosis in 5% of subjects.",
    "A single instance of pulmonary embolism was reported in a patient with no prior history of thrombotic events.",
    "Patients on the higher dose of the compound exhibited a significant increase in systolic blood pressure.",
    "Study withdrawal was attributed to unmanageable nausea and vomiting in four subjects.",
    "One participant developed a maculopapular rash that was determined to be a hypersensitivity reaction to the study medication.",
    "This is a test, nothing to see here.", # Should be false, completely out of context
    "The study was conducted in a double-blind, placebo-controlled manner.", # Should be false, in context but 0 AE
    "An adverse event of headache was reported." # Can't get much more obvious a statement
    ]

In [16]:
import torch

batch_size=4
max_length=512

all_results = []
    
# Process in batches
for i in range(0, len(gemini_ae_egs), batch_size):
    # Get the current batch
    batch_texts = gemini_ae_egs[i:i + batch_size]
    
    # Tokenize and pass to model
    inputs = tokenizer(batch_texts, return_tensors="pt", padding=True, truncation=True, max_length=max_length)
    print(batch_texts)
    with torch.no_grad():
        outputs = ae_model(**inputs)

    # Decode predictions and configure id to label map
    predictions = torch.argmax(outputs.logits, dim=1)
    print(predictions)
    id_to_label = ae_model.config.id2label
    print(id_to_label)

['Gastrointestinal bleeding occurred in two patients receiving the active treatment.One participant in the control group experienced anaphylactic shock requiring immediate medical intervention.', 'The most frequently reported adverse event was mild-to-moderate headache, observed in 15% of the study population.', 'Three cases of acute renal failure were documented, leading to discontinuation of the study drug.', 'A dose-dependent increase in serum transaminases was observed in a subset of participants.']
tensor([0, 0, 0, 0])
{0: 'LABEL_0', 1: 'LABEL_1'}
["The device's implantation was associated with local tissue necrosis in 5% of subjects.", 'A single instance of pulmonary embolism was reported in a patient with no prior history of thrombotic events.', 'Patients on the higher dose of the compound exhibited a significant increase in systolic blood pressure.', 'Study withdrawal was attributed to unmanageable nausea and vomiting in four subjects.']
tensor([0, 0, 0, 0])
{0: 'LABEL_0', 1: 'LABEL_1'}
['One participant developed a maculopapular rash that was determined to be a hypersensitivity reaction to the study medication.', 'This is a test, nothing to see here.', 'The study was conducted in a double-blind, placebo-controlled manner.', 'An adverse event of headache was reported.']
tensor([0, 0, 0, 0])
{0: 'LABEL_0', 1: 'LABEL_1'}